'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type LanguageCode = 'en' | 'zh' | 'ms' | 'ja';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Comprehensive translation dictionary for all pages
const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.login': 'Login',
    'nav.register': 'Get Started Free',

    // Hero/Landing
    'hero.badge': 'Built for Universities',
    'hero.title': 'Transform Your Classroom\nwith Real-Time Engagement',
    'hero.subtitle':
      'ThinkTap makes interactive learning seamless with real-time quizzes, instant feedback, and powerful analytics for lecturers and students.',
    'hero.ctaPrimary': 'Start Free',
    'hero.ctaSecondary': 'Watch Demo',
    'hero.note': 'No credit card required • Set up in 2 minutes • Free forever',

    // Landing Page - Features
    'landing.features.title': 'Everything You Need for Engagement',
    'landing.features.subtitle': 'Powerful features designed specifically for modern classroom environments',
    'landing.features.realTime.title': 'Real-Time Interaction',
    'landing.features.realTime.desc': 'Run live quizzes with Rush, Thinking, and Seminar modes. Students answer in real-time from any device.',
    'landing.features.questionFormats.title': 'Versatile Question Formats',
    'landing.features.questionFormats.desc': 'Multiple choice, true/false, multiple select, short and long answer questions. All in one platform.',
    'landing.features.insights.title': 'Actionable Insights',
    'landing.features.insights.desc': 'View response rates, correctness percentages, and student engagement with beautiful charts and graphs.',
    'landing.features.everywhere.title': 'Works Everywhere',
    'landing.features.everywhere.desc': 'Web and mobile apps for lecturers and students. Join sessions with a simple 6-digit code.',
    'landing.features.privacy.title': 'Privacy-First Learning',
    'landing.features.privacy.desc': 'Seminar mode enables anonymous responses for sensitive topics and open discussions.',
    'landing.features.easy.title': 'Easy to Use',
    'landing.features.easy.desc': 'Create and launch sessions in seconds. Students join instantly with no account required.',

    // Landing Page - How It Works
    'landing.howItWorks.title': 'How It Works',
    'landing.howItWorks.subtitle': 'Get started in three simple steps',
    'landing.howItWorks.step1.title': 'Create Session',
    'landing.howItWorks.step1.desc': 'Choose your question mode and create questions in seconds',
    'landing.howItWorks.step2.title': 'Students Join',
    'landing.howItWorks.step2.desc': 'Share the 6-digit code. Students join from any device instantly',
    'landing.howItWorks.step3.title': 'Engage & Analyze',
    'landing.howItWorks.step3.desc': 'Run live questions, see real-time responses, and review insights',

    // Landing Page - Pricing
    'landing.pricing.title': 'Simple, Transparent Pricing',
    'landing.pricing.subtitle': 'Choose the plan that fits your needs',
    'landing.pricing.freemium.title': 'Freemium',
    'landing.pricing.freemium.price': 'RM0',
    'landing.pricing.freemium.period': '/month',
    'landing.pricing.freemium.unlimited': 'Unlimited live sessions',
    'landing.pricing.freemium.allTypes': 'All question types',
    'landing.pricing.freemium.allModes': 'All 3 modes',
    'landing.pricing.freemium.noHistory': 'No history save',
    'landing.pricing.freemium.cta': 'Start Free',
    'landing.pricing.pro.title': 'ThinkTap Pro',
    'landing.pricing.pro.price': 'RM20',
    'landing.pricing.pro.period': '/month',
    'landing.pricing.pro.badge': 'Most Popular',
    'landing.pricing.pro.everythingFree': 'Everything in Free',
    'landing.pricing.pro.fullHistory': 'Full history',
    'landing.pricing.pro.advanced': 'Advanced analytics',
    'landing.pricing.pro.export': 'Export results',
    'landing.pricing.pro.cta': 'Subscribe',
    'landing.pricing.faculty.title': 'Faculty Plan',
    'landing.pricing.faculty.price': 'RM1K',
    'landing.pricing.faculty.period': '/month',
    'landing.pricing.faculty.everythingPro': 'Everything in Pro',
    'landing.pricing.faculty.multipleUsers': 'Multiple users',
    'landing.pricing.faculty.shared': 'Shared resources',
    'landing.pricing.faculty.branding': 'Custom branding',
    'landing.pricing.faculty.cta': 'Contact Sales',
    'landing.pricing.university.title': 'University',
    'landing.pricing.university.price': 'Custom',
    'landing.pricing.university.everythingFaculty': 'Everything in Faculty',
    'landing.pricing.university.unlimitedUsers': 'Unlimited users',
    'landing.pricing.university.lms': 'LMS integration',
    'landing.pricing.university.onPremise': 'On-premise option',
    'landing.pricing.university.cta': 'Contact Sales',

    // Landing Page - CTA
    'landing.cta.title': 'Ready to Transform Your Classroom?',
    'landing.cta.subtitle': 'Join hundreds of lecturers already using ThinkTap',
    'landing.cta.button': 'Get Started Free',
    'landing.cta.note': 'No credit card required • Set up in 2 minutes',

    // Landing Page - Footer
    'landing.footer.description': 'Interactive classroom engagement platform built for universities.',
    'landing.footer.product': 'Product',
    'landing.footer.company': 'Company',
    'landing.footer.connect': 'Connect',
    'landing.footer.features': 'Features',
    'landing.footer.pricing': 'Pricing',
    'landing.footer.docs': 'Documentation',
    'landing.footer.about': 'About',
    'landing.footer.contact': 'Contact',
    'landing.footer.privacy': 'Privacy',
    'landing.footer.terms': 'Terms',
    'landing.footer.copyright': '© 2025 ThinkTap. All rights reserved.',

    // Login
    'login.title': 'Welcome to ThinkTap',
    'login.subtitle': 'Sign in to your account to continue',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'lecturer@university.edu',
    'login.forgotPassword': 'Forgot password?',
    'login.signingIn': 'Signing in...',
    'login.signIn': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.fillAllFields': 'Please fill in all fields',
    'login.invalidCredentials': 'Invalid email or password',
    'login.success': 'Logged in successfully!',

    // Register
    'register.title': 'Create Your Account',
    'register.subtitle': 'Start creating interactive learning sessions',
    'register.confirmPassword': 'Confirm Password',
    'register.passwordHint': 'Must be at least 8 characters long',
    'register.terms': 'By creating an account, you agree to our',
    'register.termsLink': 'Terms of Service',
    'register.privacyLink': 'Privacy Policy',
    'register.and': 'and',
    'register.creating': 'Creating account...',
    'register.createAccount': 'Create Account',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.passwordTooShort': 'Password must be at least 8 characters long',
    'register.passwordsDontMatch': 'Passwords do not match',
    'register.success': 'Account created successfully!',
    'register.failed': 'Failed to create account',

    // Forgot Password
    'forgotPassword.title': 'Forgot Password',
    'forgotPassword.subtitle': 'Enter your email address and we will send you a link to reset your password',
    'forgotPassword.fillEmail': 'Please enter your email address',
    'forgotPassword.sendResetLink': 'Send Reset Link',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.success': 'Password reset link sent! Please check your email',
    'forgotPassword.failed': 'Failed to send reset link',
    'forgotPassword.checkEmail': 'Check your email for the reset link',
    'forgotPassword.emailSent': 'We have sent a password reset link to your email address. Please check your inbox and follow the instructions to reset your password.',
    'forgotPassword.backToLogin': 'Back to Login',

    // Terms
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated',
    'terms.lastUpdatedDate': 'January 2025',
    'terms.section1.title': '1. Acceptance of Terms',
    'terms.section1.content': 'By accessing and using ThinkTap, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these Terms of Service, please do not use our service.',
    'terms.section2.title': '2. Use License',
    'terms.section2.content': 'Permission is granted to temporarily use ThinkTap for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:',
    'terms.section2.point1': 'modify or copy the materials',
    'terms.section2.point2': 'use the materials for any commercial purpose or for any public display',
    'terms.section2.point3': 'attempt to reverse engineer any software contained on the service',
    'terms.section2.point4': 'remove any copyright or other proprietary notations from the materials',
    'terms.section3.title': '3. User Accounts',
    'terms.section3.content': 'You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account or password.',
    'terms.section4.title': '4. User Content',
    'terms.section4.content': 'You retain ownership of any content you submit, post, or display on or through ThinkTap. By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and distribute your content for the purpose of providing and improving our services.',
    'terms.section5.title': '5. Prohibited Uses',
    'terms.section5.content': 'You may not use ThinkTap in any way that could damage, disable, overburden, or impair the service or interfere with any other party\'s use and enjoyment of the service. Prohibited activities include but are not limited to: spamming, harassment, or any illegal activities.',
    'terms.section6.title': '6. Limitation of Liability',
    'terms.section6.content': 'ThinkTap shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the service.',
    'terms.section7.title': '7. Changes to Terms',
    'terms.section7.content': 'We reserve the right to modify these terms at any time. We will notify users of any changes by posting the new Terms of Service on this page and updating the "Last Updated" date.',
    'terms.questions': 'Have questions about these terms?',
    'terms.contactUs': 'Contact us',

    // Privacy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.lastUpdatedDate': 'January 2025',
    'privacy.section1.title': '1. Information We Collect',
    'privacy.section1.content': 'We collect information that you provide directly to us, such as when you create an account, use our services, or contact us. This may include your email address, name, and any content you create or share through ThinkTap.',
    'privacy.section2.title': '2. How We Use Your Information',
    'privacy.section2.content': 'We use the information we collect to:',
    'privacy.section2.point1': 'Provide, maintain, and improve our services',
    'privacy.section2.point2': 'Process transactions and send related information',
    'privacy.section2.point3': 'Send you technical notices and support messages',
    'privacy.section2.point4': 'Respond to your comments and questions',
    'privacy.section3.title': '3. Information Sharing',
    'privacy.section3.content': 'We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy. We may share information with service providers who assist us in operating our service, conducting our business, or serving our users.',
    'privacy.section4.title': '4. Data Security',
    'privacy.section4.content': 'We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet is 100% secure.',
    'privacy.section5.title': '5. Your Rights',
    'privacy.section5.content': 'You have the right to access, update, or delete your personal information at any time. You can do this through your account settings or by contacting us directly.',
    'privacy.section6.title': '6. Cookies',
    'privacy.section6.content': 'We use cookies and similar tracking technologies to track activity on our service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.',
    'privacy.section7.title': '7. Changes to Privacy Policy',
    'privacy.section7.content': 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.',
    'privacy.questions': 'Have questions about our privacy practices?',
    'privacy.contactUs': 'Contact us',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about ThinkTap',
    'faq.q1.question': 'What is ThinkTap?',
    'faq.q1.answer': 'ThinkTap is an interactive learning platform designed for universities and educational institutions. It enables lecturers to create and host real-time quizzes and interactive sessions with their students.',
    'faq.q2.question': 'How do students join a session?',
    'faq.q2.answer': 'Students can join a session by entering the 6-digit session code provided by their lecturer. No account is required for students to participate.',
    'faq.q3.question': 'What question types are supported?',
    'faq.q3.answer': 'ThinkTap supports multiple question types including multiple choice (single and multiple select), true/false, short answer, and long answer questions.',
    'faq.q4.question': 'Is ThinkTap free to use?',
    'faq.q4.answer': 'Yes! ThinkTap offers a free tier with unlimited live sessions and access to all question types. Premium plans are available for advanced features like full history, advanced analytics, and export capabilities.',
    'faq.q5.question': 'Can I use ThinkTap on mobile devices?',
    'faq.q5.answer': 'Yes, ThinkTap is fully responsive and works on all devices including smartphones and tablets. Both lecturers and students can use ThinkTap from any device with a web browser.',
    'faq.q6.question': 'How does the scoring system work?',
    'faq.q6.answer': 'ThinkTap uses a comprehensive scoring system that factors in correctness, response time, and streak bonuses. Faster and more accurate responses receive higher scores.',
    'faq.q7.question': 'Can sessions be anonymous?',
    'faq.q7.answer': 'Yes, ThinkTap offers a Seminar mode that allows for anonymous responses, making it ideal for sensitive topics and open discussions where students may feel more comfortable participating.',
    'faq.q8.question': 'How do I get support?',
    'faq.q8.answer': 'You can reach out to our support team through the contact page or email us at support@thinktap.com. We are here to help you get the most out of ThinkTap.',
    'faq.stillHaveQuestions': 'Still have questions?',
    'faq.contactUs': 'Contact us',

    // Dashboard
    'dashboard.title': 'ThinkTap Dashboard',
    'dashboard.welcome': 'Welcome back,',
    'dashboard.plan': 'Plan:',
    'dashboard.upgrade': 'Upgrade to Pro',
    'dashboard.signOut': 'Sign Out',
    'dashboard.totalQuizzes': 'Total Quizzes',
    'dashboard.activeNow': 'Active Now',
    'dashboard.completed': 'Completed',
    'dashboard.create': 'Create',
    'dashboard.thinktap': 'ThinkTap',
    'dashboard.thinktapDesc': 'Short interactive lessons with quizzes.',
    'dashboard.yourQuizzes': 'Your Quizzes',
    'dashboard.manageQuizzes': 'Manage and view your ThinkTap quizzes',
    'dashboard.newQuiz': 'New Quiz',
    'dashboard.loading': 'Loading...',
    'dashboard.noQuizzes': 'No quizzes yet',
    'dashboard.createFirst': 'Create your first quiz to get started',
    'dashboard.createFirstQuiz': 'Create Your First Quiz',
    'dashboard.questions': 'Questions:',
    'dashboard.sessions': 'Sessions:',
    'dashboard.updated': 'Updated:',
    'dashboard.hostLive': 'Host live',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Delete',
    'dashboard.deleteConfirm': 'Are you sure you want to delete this quiz? This cannot be undone.',
    'dashboard.failedLoad': 'Failed to load quizzes',
    'dashboard.viewReports': 'View Reports',
    'dashboard.untitledQuiz': 'Untitled Quiz',

    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'View and manage your completed quiz sessions',
    'reports.sidebarAll': 'All reports',
    'reports.sidebarTrash': 'Trash',
    'reports.headerAll': 'All reports',
    'reports.headerTrash': 'Trash',
    'reports.searchPlaceholder': 'Search',
    'reports.selectAll': 'Select all',
    'reports.sortBy': 'Sort by:',
    'reports.sort.dateDesc': 'Date (Latest first)',
    'reports.sort.dateAsc': 'Date (Oldest first)',
    'reports.sort.titleAsc': 'Title (A-Z)',
    'reports.sort.titleDesc': 'Title (Z-A)',
    'reports.emptyAll': 'No reports yet',
    'reports.emptyTrash': 'Trash is empty',
    'reports.loadError': 'Failed to load reports',
    'reports.moveToTrashSuccess': 'Report moved to trash',
    'reports.moveToTrashError': 'Failed to move report to trash',
    'reports.restoreSuccess': 'Report restored',
    'reports.restoreError': 'Failed to restore report',
    'reports.permanentDeleteConfirm':
      'Are you sure you want to permanently delete this report? This action cannot be undone.',
    'reports.permanentDeleteSuccess': 'Report permanently deleted',
    'reports.permanentDeleteError': 'Failed to delete report',
    'reports.bulkMoveLabel': 'Move selected to Trash',
    'reports.bulkMoveSuccess': 'Selected reports moved to trash',
    'reports.bulkMoveError': 'Failed to move selected reports to trash',
    'reports.bulkRestoreLabel': 'Restore selected',
    'reports.bulkRestoreSuccess': 'Selected reports restored',
    'reports.bulkRestoreError': 'Failed to restore selected reports',
    'reports.bulkPermanentDeleteLabel': 'Permanently delete selected',
    'reports.bulkPermanentDeleteSuccess': 'Selected reports permanently deleted',
    'reports.bulkPermanentDeleteError': 'Failed to permanently delete selected reports',
    'reports.badgeFinished': 'Finished',
    'reports.endedLabel': 'Ended {date}',
    'reports.participantsLabel': 'Participants',
    'reports.menu.viewQuestions': 'View Questions',
    'reports.menu.viewParticipants': 'View Participants',
    'reports.menu.viewInsights': 'View Insights',
    'reports.menu.moveToTrash': 'Move to Trash',
    'reports.menu.restore': 'Restore',
    'reports.menu.permanentlyDelete': 'Permanently Delete',
    'reports.participants.title': 'Participants',
    'reports.participants.allCount': 'All ({count})',
    'reports.participants.searchPlaceholder': 'Search',
    'reports.participants.empty': 'No participants found',
    'reports.participants.col.nickname': 'Nickname',
    'reports.participants.col.rank': 'Rank',
    'reports.participants.col.correct': 'Correct answers',
    'reports.participants.col.unanswered': 'Unanswered',
    'reports.participants.col.score': 'Final score',
    'reports.questions.title': 'Questions',
    'reports.questions.all': 'All ({count})',
    'reports.questions.difficult': 'Difficult questions ({count})',
    'reports.questions.searchPlaceholder': 'Search',
    'reports.questions.empty': 'No questions found',
    'reports.questions.col.question': 'Question',
    'reports.questions.col.type': 'Type',
    'reports.questions.col.correctIncorrect': 'Correct / Incorrect',

    // Host
    'host.title': 'Host ThinkTap',
    'host.description': 'When you press start, a colorful lobby will open with a game PIN and QR code so students can join.',
    'host.start': 'Start',

    // Session Join
    'joinSession.title': 'Join Session',
    'joinSession.subtitle': 'Enter the 6-digit code provided by your lecturer',
    'joinSession.digitsEntered': 'digits entered',
    'joinSession.joining': 'Joining...',
    'joinSession.join': 'Join Session',
    'joinSession.clear': 'Clear',
    'joinSession.noCode': "Don't have a code? Ask your lecturer or",
    'joinSession.signInLecturer': 'sign in as a lecturer',
    'joinSession.invalidCode': 'Please enter a valid 6-digit code',
    'joinSession.sessionFound': 'Session found! Enter your nickname to join.',
    'joinSession.invalidCodeError': 'Invalid session code',

    // Join Specific Session
    'joinSpecific.title': 'Join Quiz',
    'joinSpecific.subtitle': 'Enter a nickname to join this quiz.',
    'joinSpecific.duplicateNickname': 'This nickname is already being used in this quiz. Please choose another one.',
    'joinSpecific.nickname': 'Nickname',
    'joinSpecific.nicknamePlaceholder': 'Type your nickname',
    'joinSpecific.join': 'Join',
    'joinSpecific.recognizeNickname': 'Make sure you recognize your nickname on the host screen.',

    // Waiting
    'waiting.youreIn': "You're in!",
    'waiting.seeNickname': 'Did you see your nickname on screen?',
    'waiting.yourNickname': 'Your nickname',
    'waiting.waiting': 'Waiting...',
    'waiting.waitLecturer': 'Please wait while your lecturer starts the quiz.',
    'waiting.getReady': 'Get Ready!',
    'waiting.quizStarting': 'Quiz starting soon...',

    // Participant
    'participant.submit': 'Submit',
    'participant.selectAnswer': 'Please select an answer',
    'participant.selectAtLeastOne': 'Please select at least one answer',
    'participant.responseSubmitted': 'Response submitted!',
    'participant.failedSubmit': 'Failed to submit response',
    'participant.timeRemaining': 'Time Remaining',
    'participant.waitingQuestion': 'Waiting for next question...',
    'participant.sessionEnded': 'Session Ended',
    'participant.yourResults': 'Your Results',
    'participant.rank': 'Rank',
    'participant.points': 'Points',
    'participant.accuracy': 'Accuracy',
    'participant.correct': 'Correct',
    'participant.incorrect': 'Incorrect',
    'participant.totalQuestions': 'Total Questions',
    'participant.totalResponses': 'Total Responses',
    'participant.failedLoad': 'Failed to load session',
    'participant.failedLoadResults': 'Failed to load your results',
    'participant.getReady': 'Get Ready!',
    'participant.quizStarting': 'Quiz starting soon...',
    'participant.sessionCompleteTitle': 'Session Complete!',
    'participant.greatJobWithName': 'Great job, {name}!',
    'participant.greatJob': 'Great job!',
    'participant.rankOf': 'Rank #{rank}',
    'participant.outOfParticipants': 'Out of {count} participants',
    'participant.summary': 'You answered {responses} out of {questions} questions',
    'participant.enterLongAnswer': 'Type your answer...',

    // Quiz Builder
    'builder.back': 'Back',
    'builder.titlePlaceholder': 'Enter ThinkTap title...',
    'builder.thinktapDesc': 'Short interactive lessons with quizzes.',
    'builder.saving': 'Saving...',
    'builder.save': 'Save',
    'builder.quiz': 'Quiz',
    'builder.questionsInQuiz': 'Questions in this quiz',
    'builder.noQuestions': 'No questions yet. Use the editor on the right, then press',
    'builder.saveButton': 'Save',
    'builder.add': '+ Add',
    'builder.quizQuestion': 'Quiz question',
    'builder.questionPlaceholder': 'Start typing your question',
    'builder.addAnswer': 'Add more answers',
    'builder.questionType': 'Question type',
    'builder.mcSingle': 'Multiple choice • Single select',
    'builder.mcMulti': 'Multiple choice • Multiple select',
    'builder.trueFalse': 'True / False',
    'builder.timeLimit': 'Time limit (seconds)',
    'builder.points': 'Points',
    'builder.standard': 'Standard',
    'builder.double': 'Double points',
    'builder.goToOverview': 'Go to quiz overview',
    'builder.enterQuestion': 'Please enter a question',
    'builder.atLeastTwoOptions': 'Please provide at least two answer options',
    'builder.markCorrectAnswer': 'Please mark at least one correct answer',
    'builder.selectCorrectAnswer': 'Please select a correct answer',
    'builder.selectAtLeastOneCorrect': 'Please select at least one correct answer',
    'builder.questionSaved': 'Question saved',
    'builder.failedAddQuestion': 'Failed to add question',
    'builder.removeQuestion': 'Remove this question from the quiz?',
    'builder.failedRemove': 'Failed to remove question',
    'builder.untitledQuestion': 'Untitled question',
    'builder.multipleChoice': 'Multiple choice',
    'builder.trueFalseLabel': 'True / False',
    'builder.question': 'Question',
    'builder.pts': 'pts',
    'builder.addAnswerPlaceholder': 'Add answer',
    'builder.optional': '(optional)',
    'builder.seconds': 'seconds',
    'builder.minute': 'minute',
    'builder.minutes': 'minutes',
    'builder.true': 'True',
    'builder.false': 'False',
    'builder.noCorrectAnswerWarning': 'This question has no correct answer set. Please select the correct answer and save.',
    'builder.quizSettings': 'Quiz settings',
    'builder.enableMusic': 'Enable background music (lecturer only)',
    'builder.musicTrack': 'Music file name',
    'builder.musicTrackJumanji': 'Jumanji drum (Default)',
    'builder.musicTrackLofi': 'Lo-fi chill',
    'builder.musicTrackEnergetic': 'Energetic beats',
    'builder.musicTrackCalm': 'Calm piano',
    'builder.enableCountdown': 'Enable 5 second countdown before first question',
    'builder.enablePodium': 'Show podium at end of session',

    // Lecturer Session
    'lecturer.startSession': 'Start Session',
    'lecturer.endSession': 'End Session',
    'lecturer.sessionCode': 'Session Code',
    'lecturer.copyCode': 'Copy Code',
    'lecturer.codeCopied': 'Session code copied!',
    'lecturer.participantsLabel': 'Participants',
    'lecturer.noParticipants': 'No participants yet',
    'lecturer.addQuestion': 'Add Question',
    'lecturer.startQuestion': 'Start Question',
    'lecturer.endQuestion': 'End Question',
    'lecturer.showResults': 'Show Results',
    'lecturer.hideResults': 'Hide Results',
    'lecturer.viewInsights': 'View Insights',
    'lecturer.leaderboard': 'Leaderboard',
    'lecturer.questionStarted': 'Question started!',
    'lecturer.sessionStarted': 'Session started!',
    'lecturer.failedStart': 'Failed to start session',
    'lecturer.failedLoad': 'Failed to load session',
    'lecturer.failedLoadQuestions': 'Failed to load questions',
    'lecturer.noQuestions': 'No questions available. Add questions in the quiz builder.',
    'lecturer.waitingParticipants': 'Waiting for participants...',
    'lecturer.questionActive': 'Question Active',
    'lecturer.resultsShown': 'Results Shown',
    'lecturer.sessionEnded': 'Session Ended',
    'lecturer.getReady': 'Get Ready!',
    'lecturer.quizStarting': 'Quiz starting soon...',
    'lecturer.back': 'Back',
    'lecturer.connected': 'Connected',
    'lecturer.disconnected': 'Disconnected',
    'lecturer.participant': 'participant',
    'lecturer.statusCreated': 'Created',
    'lecturer.statusActive': 'Active',
    'lecturer.statusEnded': 'Ended',
    'lecturer.modeRush': 'Rush Mode',
    'lecturer.modeThinking': 'Thinking Mode',
    'lecturer.modeSeminar': 'Seminar Mode',
    'lecturer.gamePin': 'Game PIN',
    'lecturer.qrCodeAlt': 'Join quiz QR code',
    'lecturer.qrCodeInstructions': 'Students can scan the QR code or visit https://thinktap.link/session/join to enter the PIN and nickname.',
    'lecturer.firstQuestionStarting': 'First question starting soon...',
    'lecturer.nextQuestion': 'Next Question',
    'lecturer.finishSession': 'Finish Session',
    'lecturer.results': 'Results',
    'lecturer.totalResponses': 'Total Responses',
    'lecturer.correct': 'Correct',
    'lecturer.accuracy': 'Accuracy',
    'lecturer.readyToStart': 'Ready to start',
    'lecturer.question': 'question',
    'lecturer.questions': 'questions',
    'lecturer.ready': 'ready',
    'lecturer.connecting': 'Connecting to session...',
    'lecturer.loadingQuestions': 'Loading questions...',
    'lecturer.startFirstQuestion': 'Start First Question',
    'lecturer.participantJoined': 'participant joined',
    'lecturer.participantsJoined': 'participants joined',
    'lecturer.sessionComplete': 'Session Complete!',
    'lecturer.topPerformers': 'Top 3 Performers',
    'lecturer.noRankingsAvailable': 'No rankings available yet',
    'lecturer.backToDashboard': 'Back to Dashboard',
    'lecturer.failedEndSession': 'Failed to end session',
    'lecturer.notConnected': 'Not connected. Please wait...',
    'lecturer.rankingsLoadWarning': 'Could not load rankings, but session ended successfully',
    'lecturer.quiz': 'Quiz',
    'lecturer.questionAdded': 'Question added!',
    'lecturer.failedAddQuestion': 'Failed to add question',
    'lecturer.enterQuestionPlaceholder': 'Enter your question...',
    'lecturer.option': 'Option',
    'lecturer.enterCorrectAnswer': 'Enter correct answer...',
    'lecturer.createQuestionDescription': 'Create a new question for your session',
    'lecturer.options': 'Options',
    'lecturer.correctAnswer': 'Correct Answer',

    // Join Session
    'join.title': 'Join Session',
    'join.description': 'Enter the 6-digit code provided by your lecturer',
    'join.button': 'Join Session',
    'join.joining': 'Joining...',
    'join.clear': 'Clear',
    'join.digitsEntered': '{count}/6 digits entered',
    'join.invalidCode': 'Please enter a valid 6-digit code',
    'join.sessionFound': 'Session found! Enter your nickname to join.',
    'join.noCode': "Don't have a code? Ask your lecturer or",
    'join.signInAsLecturer': 'sign in as a lecturer',

    // Common
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
  },
  zh: {
    // Navigation
    'nav.features': '功能',
    'nav.howItWorks': '如何运作',
    'nav.pricing': '价格',
    'nav.faq': '常见问题',
    'nav.login': '登录',
    'nav.register': '免费开始',

    // Hero/Landing
    'hero.badge': '为大学而建',
    'hero.title': '用实时互动\n改变你的课堂',
    'hero.subtitle':
      'ThinkTap 通过实时测验、即时反馈和强大的分析，让互动教学变得轻松简单。',
    'hero.ctaPrimary': '免费开始',
    'hero.ctaSecondary': '观看示范',
    'hero.note': '无需信用卡 • 2 分钟完成设置 • 永久免费方案',

    // Landing Page - Features
    'landing.features.title': '您需要的所有互动功能',
    'landing.features.subtitle': '专为现代课堂环境设计的强大功能',
    'landing.features.realTime.title': '实时互动',
    'landing.features.realTime.desc': '使用 Rush、Thinking 和 Seminar 模式进行实时测验。学生可从任何设备实时回答。',
    'landing.features.questionFormats.title': '多样化的问题格式',
    'landing.features.questionFormats.desc': '单选题、判断题、多选题、简答题和论述题。全部集成在一个平台上。',
    'landing.features.insights.title': '可操作的洞察',
    'landing.features.insights.desc': '通过精美的图表查看响应率、正确率百分比和学生参与度。',
    'landing.features.everywhere.title': '随处可用',
    'landing.features.everywhere.desc': '为讲师和学生提供网页和移动应用。使用简单的 6 位数字代码加入课程。',
    'landing.features.privacy.title': '隐私优先的学习',
    'landing.features.privacy.desc': 'Seminar 模式支持敏感话题和开放讨论的匿名回答。',
    'landing.features.easy.title': '易于使用',
    'landing.features.easy.desc': '在几秒钟内创建和启动课程。学生无需账户即可即时加入。',

    // Landing Page - How It Works
    'landing.howItWorks.title': '工作原理',
    'landing.howItWorks.subtitle': '三个简单步骤即可开始',
    'landing.howItWorks.step1.title': '创建课程',
    'landing.howItWorks.step1.desc': '选择问题模式并在几秒钟内创建问题',
    'landing.howItWorks.step2.title': '学生加入',
    'landing.howItWorks.step2.desc': '分享 6 位数字代码。学生可从任何设备即时加入',
    'landing.howItWorks.step3.title': '互动与分析',
    'landing.howItWorks.step3.desc': '运行实时问题，查看实时响应并审查洞察',

    // Landing Page - Pricing
    'landing.pricing.title': '简单透明的定价',
    'landing.pricing.subtitle': '选择适合您需求的计划',
    'landing.pricing.freemium.title': '免费版',
    'landing.pricing.freemium.price': 'RM0',
    'landing.pricing.freemium.period': '/月',
    'landing.pricing.freemium.unlimited': '无限实时课程',
    'landing.pricing.freemium.allTypes': '所有问题类型',
    'landing.pricing.freemium.allModes': '所有 3 种模式',
    'landing.pricing.freemium.noHistory': '不保存历史',
    'landing.pricing.freemium.cta': '免费开始',
    'landing.pricing.pro.title': 'ThinkTap Pro',
    'landing.pricing.pro.price': 'RM20',
    'landing.pricing.pro.period': '/月',
    'landing.pricing.pro.badge': '最受欢迎',
    'landing.pricing.pro.everythingFree': '包含免费版所有功能',
    'landing.pricing.pro.fullHistory': '完整历史记录',
    'landing.pricing.pro.advanced': '高级分析',
    'landing.pricing.pro.export': '导出结果',
    'landing.pricing.pro.cta': '订阅',
    'landing.pricing.faculty.title': '教师计划',
    'landing.pricing.faculty.price': 'RM1K',
    'landing.pricing.faculty.period': '/月',
    'landing.pricing.faculty.everythingPro': '包含 Pro 版所有功能',
    'landing.pricing.faculty.multipleUsers': '多用户',
    'landing.pricing.faculty.shared': '共享资源',
    'landing.pricing.faculty.branding': '自定义品牌',
    'landing.pricing.faculty.cta': '联系销售',
    'landing.pricing.university.title': '大学',
    'landing.pricing.university.price': '定制',
    'landing.pricing.university.everythingFaculty': '包含教师版所有功能',
    'landing.pricing.university.unlimitedUsers': '无限用户',
    'landing.pricing.university.lms': 'LMS 集成',
    'landing.pricing.university.onPremise': '本地部署选项',
    'landing.pricing.university.cta': '联系销售',

    // Landing Page - CTA
    'landing.cta.title': '准备好改变您的课堂了吗？',
    'landing.cta.subtitle': '加入数百名已经在使用 ThinkTap 的讲师',
    'landing.cta.button': '免费开始',
    'landing.cta.note': '无需信用卡 • 2 分钟完成设置',

    // Landing Page - Footer
    'landing.footer.description': '为大学打造的互动课堂参与平台。',
    'landing.footer.product': '产品',
    'landing.footer.company': '公司',
    'landing.footer.connect': '联系',
    'landing.footer.features': '功能',
    'landing.footer.pricing': '价格',
    'landing.footer.docs': '文档',
    'landing.footer.about': '关于',
    'landing.footer.contact': '联系我们',
    'landing.footer.privacy': '隐私',
    'landing.footer.terms': '条款',
    'landing.footer.copyright': '© 2025 ThinkTap。保留所有权利。',

    // Login
    'login.title': '欢迎使用 ThinkTap',
    'login.subtitle': '登录您的账户以继续',
    'login.email': '电子邮件',
    'login.password': '密码',
    'login.emailPlaceholder': 'lecturer@university.edu',
    'login.forgotPassword': '忘记密码？',
    'login.signingIn': '正在登录...',
    'login.signIn': '登录',
    'login.noAccount': '还没有账户？',
    'login.signUp': '注册',
    'login.fillAllFields': '请填写所有字段',
    'login.invalidCredentials': '电子邮件或密码无效',
    'login.success': '登录成功！',

    // Register
    'register.title': '创建您的账户',
    'register.subtitle': '开始创建互动学习课程',
    'register.confirmPassword': '确认密码',
    'register.passwordHint': '必须至少 8 个字符',
    'register.terms': '创建账户即表示您同意我们的',
    'register.termsLink': '服务条款',
    'register.privacyLink': '隐私政策',
    'register.and': '和',
    'register.creating': '正在创建账户...',
    'register.createAccount': '创建账户',
    'register.haveAccount': '已有账户？',
    'register.signIn': '登录',
    'register.passwordTooShort': '密码必须至少 8 个字符',
    'register.passwordsDontMatch': '密码不匹配',
    'register.success': '账户创建成功！',
    'register.failed': '创建账户失败',

    // Forgot Password
    'forgotPassword.title': '忘记密码',
    'forgotPassword.subtitle': '请输入您的电子邮件地址，我们将向您发送重置密码的链接',
    'forgotPassword.fillEmail': '请输入您的电子邮件地址',
    'forgotPassword.sendResetLink': '发送重置链接',
    'forgotPassword.sending': '发送中...',
    'forgotPassword.success': '密码重置链接已发送！请查看您的电子邮件',
    'forgotPassword.failed': '发送重置链接失败',
    'forgotPassword.checkEmail': '请查看您的电子邮件以获取重置链接',
    'forgotPassword.emailSent': '我们已向您的电子邮件地址发送了密码重置链接。请查看您的收件箱并按照说明重置密码。',
    'forgotPassword.backToLogin': '返回登录',

    // Terms
    'terms.title': '服务条款',
    'terms.lastUpdated': '最后更新',
    'terms.lastUpdatedDate': '2025年1月',
    'terms.section1.title': '1. 接受条款',
    'terms.section1.content': '通过访问和使用 ThinkTap，您接受并同意受本协议的条款和规定约束。如果您不同意这些服务条款，请不要使用我们的服务。',
    'terms.section2.title': '2. 使用许可',
    'terms.section2.content': '我们授予您临时使用 ThinkTap 进行个人、非商业临时查看的许可。这是许可的授予，不是所有权的转移，在此许可下您不得：',
    'terms.section2.point1': '修改或复制材料',
    'terms.section2.point2': '将材料用于任何商业目的或任何公开展示',
    'terms.section2.point3': '尝试对服务中包含的任何软件进行逆向工程',
    'terms.section2.point4': '从材料中删除任何版权或其他专有标记',
    'terms.section3.title': '3. 用户账户',
    'terms.section3.content': '您有责任维护账户和密码的机密性。您同意对在您账户或密码下发生的所有活动承担责任。',
    'terms.section4.title': '4. 用户内容',
    'terms.section4.content': '您保留在 ThinkTap 上或通过 ThinkTap 提交、发布或显示的任何内容的所有权。通过提交内容，您授予我们在全球范围内非独占、免版税的使用、复制和分发您的内容的许可，以提供和改进我们的服务。',
    'terms.section5.title': '5. 禁止用途',
    'terms.section5.content': '您不得以任何可能损坏、禁用、超载或损害服务或干扰任何其他方使用和享受服务的方式使用 ThinkTap。禁止的活动包括但不限于：垃圾邮件、骚扰或任何非法活动。',
    'terms.section6.title': '6. 责任限制',
    'terms.section6.content': 'ThinkTap 不对任何间接、偶然、特殊、后果性或惩罚性损害，或任何利润或收入损失（无论是直接还是间接产生的），或任何数据、使用权、商誉或其他无形损失承担责任，这些损失是由于您使用服务而产生的。',
    'terms.section7.title': '7. 条款变更',
    'terms.section7.content': '我们保留随时修改这些条款的权利。我们将通过在此页面上发布新的服务条款并更新"最后更新"日期来通知用户任何变更。',
    'terms.questions': '对这些条款有疑问？',
    'terms.contactUs': '联系我们',

    // Privacy
    'privacy.title': '隐私政策',
    'privacy.lastUpdated': '最后更新',
    'privacy.lastUpdatedDate': '2025年1月',
    'privacy.section1.title': '1. 我们收集的信息',
    'privacy.section1.content': '我们收集您直接提供给我们的信息，例如当您创建账户、使用我们的服务或联系我们时。这可能包括您的电子邮件地址、姓名以及您通过 ThinkTap 创建或分享的任何内容。',
    'privacy.section2.title': '2. 我们如何使用您的信息',
    'privacy.section2.content': '我们使用收集的信息来：',
    'privacy.section2.point1': '提供、维护和改进我们的服务',
    'privacy.section2.point2': '处理交易并发送相关信息',
    'privacy.section2.point3': '向您发送技术通知和支持消息',
    'privacy.section2.point4': '回复您的评论和问题',
    'privacy.section3.title': '3. 信息共享',
    'privacy.section3.content': '未经您的同意，我们不会出售、交易或以其他方式将您的个人信息转移给第三方，除非本政策中另有说明。我们可能会与协助我们运营服务、开展业务或为我们的用户提供服务的服务提供商共享信息。',
    'privacy.section4.title': '4. 数据安全',
    'privacy.section4.content': '我们实施适当的技术和组织措施，以保护您的个人信息免受未经授权的访问、更改、披露或破坏。但是，通过互联网传输的方法都不是 100% 安全的。',
    'privacy.section5.title': '5. 您的权利',
    'privacy.section5.content': '您有权随时访问、更新或删除您的个人信息。您可以通过账户设置或直接联系我们来执行此操作。',
    'privacy.section6.title': '6. Cookie',
    'privacy.section6.content': '我们使用 Cookie 和类似的跟踪技术来跟踪我们服务上的活动并保存某些信息。您可以指示浏览器拒绝所有 Cookie 或在发送 Cookie 时提示。',
    'privacy.section7.title': '7. 隐私政策的变更',
    'privacy.section7.content': '我们可能会不时更新我们的隐私政策。我们将通过在此页面上发布新的隐私政策并更新"最后更新"日期来通知您任何变更。',
    'privacy.questions': '对我们的隐私做法有疑问？',
    'privacy.contactUs': '联系我们',

    // FAQ
    'faq.title': '常见问题',
    'faq.subtitle': '查找关于 ThinkTap 的常见问题答案',
    'faq.q1.question': '什么是 ThinkTap？',
    'faq.q1.answer': 'ThinkTap 是一个专为大学和教育机构设计的互动学习平台。它使讲师能够创建并主持与学生进行的实时测验和互动课程。',
    'faq.q2.question': '学生如何加入课程？',
    'faq.q2.answer': '学生可以通过输入讲师提供的 6 位数字课程代码加入课程。学生参与不需要账户。',
    'faq.q3.question': '支持哪些问题类型？',
    'faq.q3.answer': 'ThinkTap 支持多种问题类型，包括多选题（单选和多选）、判断题、简答题和论述题。',
    'faq.q4.question': 'ThinkTap 是免费使用的吗？',
    'faq.q4.answer': '是的！ThinkTap 提供免费版本，包含无限实时课程和所有问题类型的访问。高级计划提供完整历史记录、高级分析和导出功能等高级功能。',
    'faq.q5.question': '我可以在移动设备上使用 ThinkTap 吗？',
    'faq.q5.answer': '是的，ThinkTap 完全响应式，可在包括智能手机和平板电脑在内的所有设备上使用。讲师和学生都可以从任何带有网络浏览器的设备使用 ThinkTap。',
    'faq.q6.question': '评分系统如何工作？',
    'faq.q6.answer': 'ThinkTap 使用综合考虑正确性、响应时间和连胜奖励的综合评分系统。更快、更准确的响应会获得更高的分数。',
    'faq.q7.question': '课程可以是匿名的吗？',
    'faq.q7.answer': '是的，ThinkTap 提供 Seminar 模式，允许匿名回答，非常适合敏感话题和公开讨论，学生可能更愿意参与。',
    'faq.q8.question': '如何获得支持？',
    'faq.q8.answer': '您可以通过联系页面联系我们的支持团队，或发送电子邮件至 support@thinktap.com。我们随时为您提供帮助，让您充分利用 ThinkTap。',
    'faq.stillHaveQuestions': '还有问题？',
    'faq.contactUs': '联系我们',

    // Dashboard
    'dashboard.title': 'ThinkTap 仪表板',
    'dashboard.welcome': '欢迎回来，',
    'dashboard.plan': '计划：',
    'dashboard.upgrade': '升级到专业版',
    'dashboard.signOut': '退出',
    'dashboard.totalQuizzes': '总测验数',
    'dashboard.activeNow': '当前活跃',
    'dashboard.completed': '已完成',
    'dashboard.create': '创建',
    'dashboard.thinktap': 'ThinkTap',
    'dashboard.thinktapDesc': '简短的互动课程与测验。',
    'dashboard.yourQuizzes': '您的测验',
    'dashboard.manageQuizzes': '管理和查看您的 ThinkTap 测验',
    'dashboard.newQuiz': '新建测验',
    'dashboard.loading': '加载中...',
    'dashboard.noQuizzes': '还没有测验',
    'dashboard.createFirst': '创建您的第一个测验开始',
    'dashboard.createFirstQuiz': '创建您的第一个测验',
    'dashboard.questions': '问题：',
    'dashboard.sessions': '课程：',
    'dashboard.updated': '更新：',
    'dashboard.hostLive': '直播',
    'dashboard.edit': '编辑',
    'dashboard.delete': '删除',
    'dashboard.deleteConfirm': '您确定要删除此测验吗？此操作无法撤销。',
    'dashboard.failedLoad': '加载测验失败',
    'dashboard.viewReports': '查看报告',
    'dashboard.untitledQuiz': '未命名测验',

    // Reports
    'reports.title': '报告',
    'reports.subtitle': '查看和管理您已完成的测验会话',
    'reports.sidebarAll': '所有报告',
    'reports.sidebarTrash': '回收站',
    'reports.headerAll': '所有报告',
    'reports.headerTrash': '回收站',
    'reports.searchPlaceholder': '搜索',
    'reports.selectAll': '全选',
    'reports.sortBy': '排序方式：',
    'reports.sort.dateDesc': '日期（最新优先）',
    'reports.sort.dateAsc': '日期（最旧优先）',
    'reports.sort.titleAsc': '标题（A-Z）',
    'reports.sort.titleDesc': '标题（Z-A）',
    'reports.emptyAll': '暂时没有报告',
    'reports.emptyTrash': '回收站为空',
    'reports.loadError': '加载报告失败',
    'reports.moveToTrashSuccess': '报告已移至回收站',
    'reports.moveToTrashError': '移动报告到回收站失败',
    'reports.restoreSuccess': '报告已恢复',
    'reports.restoreError': '恢复报告失败',
    'reports.permanentDeleteConfirm': '确定要永久删除此报告吗？此操作无法撤销。',
    'reports.permanentDeleteSuccess': '报告已永久删除',
    'reports.permanentDeleteError': '删除报告失败',
    'reports.bulkMoveLabel': '将所选移至回收站',
    'reports.bulkMoveSuccess': '所选报告已移至回收站',
    'reports.bulkMoveError': '移动所选报告到回收站失败',
    'reports.bulkRestoreLabel': '恢复所选报告',
    'reports.bulkRestoreSuccess': '所选报告已恢复',
    'reports.bulkRestoreError': '恢复所选报告失败',
    'reports.bulkPermanentDeleteLabel': '永久删除所选报告',
    'reports.bulkPermanentDeleteSuccess': '所选报告已永久删除',
    'reports.bulkPermanentDeleteError': '永久删除所选报告失败',
    'reports.badgeFinished': '已完成',
    'reports.endedLabel': '结束时间 {date}',
    'reports.participantsLabel': '参与者',
    'reports.menu.viewQuestions': '查看问题',
    'reports.menu.viewParticipants': '查看参与者',
    'reports.menu.viewInsights': '查看洞察',
    'reports.menu.moveToTrash': '移至回收站',
    'reports.menu.restore': '恢复',
    'reports.menu.permanentlyDelete': '永久删除',
    'reports.participants.title': '参与者',
    'reports.participants.allCount': '全部（{count}）',
    'reports.participants.searchPlaceholder': '搜索',
    'reports.participants.empty': '未找到参与者',
    'reports.participants.col.nickname': '昵称',
    'reports.participants.col.rank': '排名',
    'reports.participants.col.correct': '答对题数',
    'reports.participants.col.unanswered': '未作答',
    'reports.participants.col.score': '最终得分',
    'reports.questions.title': '问题',
    'reports.questions.all': '全部（{count}）',
    'reports.questions.difficult': '困难问题（{count}）',
    'reports.questions.searchPlaceholder': '搜索',
    'reports.questions.empty': '未找到问题',
    'reports.questions.col.question': '问题',
    'reports.questions.col.type': '类型',
    'reports.questions.col.correctIncorrect': '正确 / 错误',

    // Host
    'host.title': '主持 ThinkTap',
    'host.description': '当您按开始后，将打开一个彩色大厅，显示游戏 PIN 和二维码，以便学生加入。',
    'host.start': '开始',

    // Session Join
    'joinSession.title': '加入课程',
    'joinSession.subtitle': '输入讲师提供的 6 位数字代码',
    'joinSession.digitsEntered': '位数字已输入',
    'joinSession.joining': '正在加入...',
    'joinSession.join': '加入课程',
    'joinSession.clear': '清除',
    'joinSession.noCode': '没有代码？询问您的讲师或',
    'joinSession.signInLecturer': '以讲师身份登录',
    'joinSession.invalidCode': '请输入有效的 6 位数字代码',
    'joinSession.sessionFound': '找到课程！输入您的昵称加入。',
    'joinSession.invalidCodeError': '无效的课程代码',

    // Join Specific Session
    'joinSpecific.title': '加入测验',
    'joinSpecific.subtitle': '输入昵称加入此测验。',
    'joinSpecific.duplicateNickname': '此昵称已在此测验中使用。请选择另一个。',
    'joinSpecific.nickname': '昵称',
    'joinSpecific.nicknamePlaceholder': '输入您的昵称',
    'joinSpecific.join': '加入',
    'joinSpecific.recognizeNickname': '确保您能在主机屏幕上识别您的昵称。',

    // Waiting
    'waiting.youreIn': '您已加入！',
    'waiting.seeNickname': '您在屏幕上看到您的昵称了吗？',
    'waiting.yourNickname': '您的昵称',
    'waiting.waiting': '等待中...',
    'waiting.waitLecturer': '请等待讲师开始测验。',
    'waiting.getReady': '准备就绪！',
    'waiting.quizStarting': '测验即将开始...',

    // Participant
    'participant.submit': '提交',
    'participant.selectAnswer': '请选择一个答案',
    'participant.selectAtLeastOne': '请至少选择一个答案',
    'participant.responseSubmitted': '答案已提交！',
    'participant.failedSubmit': '提交答案失败',
    'participant.timeRemaining': '剩余时间',
    'participant.waitingQuestion': '等待下一题...',
    'participant.sessionEnded': '课程已结束',
    'participant.yourResults': '您的结果',
    'participant.rank': '排名',
    'participant.points': '分数',
    'participant.accuracy': '准确率',
    'participant.correct': '正确',
    'participant.incorrect': '错误',
    'participant.totalQuestions': '总问题数',
    'participant.totalResponses': '总回答数',
    'participant.failedLoad': '加载课程失败',
    'participant.failedLoadResults': '加载您的结果失败',
    'participant.getReady': '准备就绪！',
    'participant.quizStarting': '测验即将开始...',
    'participant.sessionCompleteTitle': '课程结束！',
    'participant.greatJobWithName': '{name}，做得好！',
    'participant.greatJob': '做得好！',
    'participant.rankOf': '排名第 {rank} 名',
    'participant.outOfParticipants': '共 {count} 名参与者',
    'participant.summary': '您共回答了 {questions} 道题中的 {responses} 道',

    // Quiz Builder
    'builder.back': '返回',
    'builder.titlePlaceholder': '输入 ThinkTap 标题...',
    'builder.thinktapDesc': '简短的互动课程与测验。',
    'builder.saving': '保存中...',
    'builder.save': '保存',
    'builder.quiz': '测验',
    'builder.questionsInQuiz': '此测验中的问题',
    'builder.noQuestions': '还没有问题。使用右侧的编辑器，然后按',
    'builder.saveButton': '保存',
    'builder.add': '+ 添加',
    'builder.quizQuestion': '测验问题',
    'builder.questionPlaceholder': '开始输入您的问题',
    'builder.addAnswer': '添加更多答案',
    'builder.questionType': '问题类型',
    'builder.mcSingle': '多选题 • 单选',
    'builder.mcMulti': '多选题 • 多选',
    'builder.trueFalse': '对 / 错',
    'builder.timeLimit': '时间限制（秒）',
    'builder.points': '分数',
    'builder.standard': '标准',
    'builder.double': '双倍分数',
    'builder.goToOverview': '转到测验概览',
    'builder.enterQuestion': '请输入问题',
    'builder.atLeastTwoOptions': '请提供至少两个答案选项',
    'builder.markCorrectAnswer': '请标记至少一个正确答案',
    'builder.selectCorrectAnswer': '请选择正确答案',
    'builder.selectAtLeastOneCorrect': '请至少选择一个正确答案',
    'builder.questionSaved': '问题已保存',
    'builder.failedAddQuestion': '添加问题失败',
    'builder.removeQuestion': '从测验中移除此问题？',
    'builder.failedRemove': '移除问题失败',
    'builder.untitledQuestion': '未命名问题',
    'builder.multipleChoice': '多选题',
    'builder.trueFalseLabel': '对 / 错',
    'builder.question': '问题',
    'builder.pts': '分',
    'builder.addAnswerPlaceholder': '添加答案',
    'builder.optional': '（可选）',
    'builder.quizSettings': '测验设置',
    'builder.enableMusic': '启用背景音乐（仅讲师端）',
    'builder.musicTrack': '音乐文件名',
    'builder.musicTrackJumanji': 'Jumanji 鼓点（默认）',
    'builder.musicTrackLofi': 'Lo-fi 轻松音乐',
    'builder.musicTrackEnergetic': '动感节奏',
    'builder.musicTrackCalm': '舒缓钢琴',
    'builder.enableCountdown': '在第一题前启用 5 秒倒计时',
    'builder.enablePodium': '在课程结束时显示颁奖台',

    // Lecturer Session
    'lecturer.startSession': '开始课程',
    'lecturer.endSession': '结束课程',
    'lecturer.sessionCode': '课程代码',
    'lecturer.copyCode': '复制代码',
    'lecturer.codeCopied': '课程代码已复制！',
    'lecturer.participants': '参与者',
    'lecturer.noParticipants': '还没有参与者',
    'lecturer.addQuestion': '添加问题',
    'lecturer.startQuestion': '开始问题',
    'lecturer.endQuestion': '结束问题',
    'lecturer.showResults': '显示结果',
    'lecturer.hideResults': '隐藏结果',
    'lecturer.viewInsights': '查看洞察',
    'lecturer.leaderboard': '排行榜',
    'lecturer.questionStarted': '问题已开始！',
    'lecturer.sessionStarted': '课程已开始！',
    'lecturer.failedStart': '开始课程失败',
    'lecturer.failedLoad': '加载课程失败',
    'lecturer.failedLoadQuestions': '加载问题失败',
    'lecturer.noQuestions': '没有可用问题。在测验构建器中添加问题。',
    'lecturer.waitingParticipants': '等待参与者...',
    'lecturer.questionActive': '问题进行中',
    'lecturer.resultsShown': '结果已显示',
    'lecturer.sessionEnded': '课程已结束',
    'lecturer.getReady': '准备就绪！',
    'lecturer.quizStarting': '测验即将开始...',
    'lecturer.statusCreated': '已创建',
    'lecturer.statusActive': '进行中',
    'lecturer.statusEnded': '已结束',
    'lecturer.modeRush': '快速模式',
    'lecturer.modeThinking': '思考模式',
    'lecturer.modeSeminar': '研讨模式',
    'lecturer.gamePin': '游戏 PIN',
    'lecturer.qrCodeAlt': '加入测验二维码',
    'lecturer.qrCodeInstructions': '学生可以扫描二维码或访问 https://thinktap.link/session/join 以输入 PIN 和昵称。',
    'lecturer.firstQuestionStarting': '第一题即将开始...',
    'lecturer.readyToStart': '准备开始',
    'lecturer.question': '个问题',
    'lecturer.questions': '个问题',
    'lecturer.ready': '准备就绪',
    'lecturer.startFirstQuestion': '开始第一题',

    // Join Session
    'join.title': '加入课程',
    'join.description': '输入讲师提供的6位数字代码',
    'join.button': '加入课程',
    'join.joining': '正在加入...',
    'join.clear': '清除',
    'join.digitsEntered': '已输入 {count}/6 位数字',
    'join.invalidCode': '请输入有效的6位数字代码',
    'join.sessionFound': '找到课程！请输入您的昵称加入。',
    'join.noCode': '没有代码？请询问您的讲师或',
    'join.signInAsLecturer': '以讲师身份登录',

    // Common
    'common.loading': '加载中...',
    'common.back': '返回',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',
  },
  ms: {
    // Navigation
    'nav.features': 'Ciri-ciri',
    'nav.howItWorks': 'Cara Berfungsi',
    'nav.pricing': 'Harga',
    'nav.faq': 'Soalan Lazim',
    'nav.login': 'Log Masuk',
    'nav.register': 'Mulakan Percuma',

    // Hero/Landing
    'hero.badge': 'Dibina untuk Universiti',
    'hero.title': 'Ubah Suai Bilik Kuliah Anda\nDengan Penglibatan Masa Nyata',
    'hero.subtitle':
      'ThinkTap memudahkan pembelajaran interaktif dengan kuiz masa nyata, maklum balas segera, dan analitik yang berkuasa.',
    'hero.ctaPrimary': 'Mulakan Percuma',
    'hero.ctaSecondary': 'Tonton Demo',
    'hero.note':
      'Tiada kad kredit diperlukan • Sedia dalam 2 minit • Percuma selama-lamanya',

    // Landing Page - Features
    'landing.features.title': 'Segala Yang Anda Perlukan untuk Penglibatan',
    'landing.features.subtitle': 'Ciri-ciri berkuasa yang direka khusus untuk persekitaran bilik darjah moden',
    'landing.features.realTime.title': 'Interaksi Masa Nyata',
    'landing.features.realTime.desc': 'Jalankan kuiz langsung dengan mod Rush, Thinking, dan Seminar. Pelajar menjawab secara masa nyata dari mana-mana peranti.',
    'landing.features.questionFormats.title': 'Format Soalan Serba Boleh',
    'landing.features.questionFormats.desc': 'Pilihan berganda, benar/salah, pilihan berganda berbilang, soalan jawapan pendek dan panjang. Semua dalam satu platform.',
    'landing.features.insights.title': 'Wawasan Boleh Tindakan',
    'landing.features.insights.desc': 'Lihat kadar respons, peratusan ketepatan, dan penglibatan pelajar dengan carta dan graf yang cantik.',
    'landing.features.everywhere.title': 'Berfungsi Di Mana-mana',
    'landing.features.everywhere.desc': 'Aplikasi web dan mudah alih untuk pensyarah dan pelajar. Sertai sesi dengan kod 6 digit yang mudah.',
    'landing.features.privacy.title': 'Pembelajaran Utama Privasi',
    'landing.features.privacy.desc': 'Mod Seminar membolehkan respons tanpa nama untuk topik sensitif dan perbincangan terbuka.',
    'landing.features.easy.title': 'Mudah Digunakan',
    'landing.features.easy.desc': 'Cipta dan lancarkan sesi dalam beberapa saat. Pelajar menyertai dengan serta-merta tanpa memerlukan akaun.',

    // Landing Page - How It Works
    'landing.howItWorks.title': 'Cara Berfungsi',
    'landing.howItWorks.subtitle': 'Mulakan dalam tiga langkah mudah',
    'landing.howItWorks.step1.title': 'Cipta Sesi',
    'landing.howItWorks.step1.desc': 'Pilih mod soalan anda dan cipta soalan dalam beberapa saat',
    'landing.howItWorks.step2.title': 'Pelajar Menyertai',
    'landing.howItWorks.step2.desc': 'Kongsi kod 6 digit. Pelajar menyertai dari mana-mana peranti dengan serta-merta',
    'landing.howItWorks.step3.title': 'Terlibat & Analisis',
    'landing.howItWorks.step3.desc': 'Jalankan soalan langsung, lihat respons masa nyata, dan semak wawasan',

    // Landing Page - Pricing
    'landing.pricing.title': 'Harga Mudah dan Telus',
    'landing.pricing.subtitle': 'Pilih pelan yang sesuai dengan keperluan anda',
    'landing.pricing.freemium.title': 'Freemium',
    'landing.pricing.freemium.price': 'RM0',
    'landing.pricing.freemium.period': '/bulan',
    'landing.pricing.freemium.unlimited': 'Sesi langsung tanpa had',
    'landing.pricing.freemium.allTypes': 'Semua jenis soalan',
    'landing.pricing.freemium.allModes': 'Semua 3 mod',
    'landing.pricing.freemium.noHistory': 'Tiada simpanan sejarah',
    'landing.pricing.freemium.cta': 'Mulakan Percuma',
    'landing.pricing.pro.title': 'ThinkTap Pro',
    'landing.pricing.pro.price': 'RM20',
    'landing.pricing.pro.period': '/bulan',
    'landing.pricing.pro.badge': 'Paling Popular',
    'landing.pricing.pro.everythingFree': 'Segala-galanya dalam Percuma',
    'landing.pricing.pro.fullHistory': 'Sejarah penuh',
    'landing.pricing.pro.advanced': 'Analitik lanjutan',
    'landing.pricing.pro.export': 'Eksport keputusan',
    'landing.pricing.pro.cta': 'Langgan',
    'landing.pricing.faculty.title': 'Pelan Fakulti',
    'landing.pricing.faculty.price': 'RM1K',
    'landing.pricing.faculty.period': '/bulan',
    'landing.pricing.faculty.everythingPro': 'Segala-galanya dalam Pro',
    'landing.pricing.faculty.multipleUsers': 'Pelbagai pengguna',
    'landing.pricing.faculty.shared': 'Sumber dikongsi',
    'landing.pricing.faculty.branding': 'Pemasaran tersuai',
    'landing.pricing.faculty.cta': 'Hubungi Jualan',
    'landing.pricing.university.title': 'Universiti',
    'landing.pricing.university.price': 'Tersuai',
    'landing.pricing.university.everythingFaculty': 'Segala-galanya dalam Fakulti',
    'landing.pricing.university.unlimitedUsers': 'Pengguna tanpa had',
    'landing.pricing.university.lms': 'Integrasi LMS',
    'landing.pricing.university.onPremise': 'Pilihan on-premise',
    'landing.pricing.university.cta': 'Hubungi Jualan',

    // Landing Page - CTA
    'landing.cta.title': 'Bersedia untuk Mengubah Bilik Darjah Anda?',
    'landing.cta.subtitle': 'Sertai beratus-ratus pensyarah yang sudah menggunakan ThinkTap',
    'landing.cta.button': 'Mulakan Percuma',
    'landing.cta.note': 'Tiada kad kredit diperlukan • Sedia dalam 2 minit',

    // Landing Page - Footer
    'landing.footer.description': 'Platform penglibatan bilik darjah interaktif yang dibina untuk universiti.',
    'landing.footer.product': 'Produk',
    'landing.footer.company': 'Syarikat',
    'landing.footer.connect': 'Berhubung',
    'landing.footer.features': 'Ciri-ciri',
    'landing.footer.pricing': 'Harga',
    'landing.footer.docs': 'Dokumentasi',
    'landing.footer.about': 'Tentang',
    'landing.footer.contact': 'Hubungi',
    'landing.footer.privacy': 'Privasi',
    'landing.footer.terms': 'Terma',
    'landing.footer.copyright': '© 2025 ThinkTap. Hak cipta terpelihara.',

    // Login
    'login.title': 'Selamat Datang ke ThinkTap',
    'login.subtitle': 'Log masuk ke akaun anda untuk meneruskan',
    'login.email': 'E-mel',
    'login.password': 'Kata Laluan',
    'login.emailPlaceholder': 'lecturer@university.edu',
    'login.forgotPassword': 'Lupa kata laluan?',
    'login.signingIn': 'Sedang log masuk...',
    'login.signIn': 'Log Masuk',
    'login.noAccount': 'Tiada akaun?',
    'login.signUp': 'Daftar',
    'login.fillAllFields': 'Sila isi semua medan',
    'login.invalidCredentials': 'E-mel atau kata laluan tidak sah',
    'login.success': 'Log masuk berjaya!',

    // Register
    'register.title': 'Cipta Akaun Anda',
    'register.subtitle': 'Mula mencipta sesi pembelajaran interaktif',
    'register.confirmPassword': 'Sahkan Kata Laluan',
    'register.passwordHint': 'Mesti sekurang-kurangnya 8 aksara',
    'register.terms': 'Dengan mencipta akaun, anda bersetuju dengan',
    'register.termsLink': 'Terma Perkhidmatan',
    'register.privacyLink': 'Dasar Privasi',
    'register.and': 'dan',
    'register.creating': 'Sedang mencipta akaun...',
    'register.createAccount': 'Cipta Akaun',
    'register.haveAccount': 'Sudah ada akaun?',
    'register.signIn': 'Log masuk',
    'register.passwordTooShort': 'Kata laluan mesti sekurang-kurangnya 8 aksara',
    'register.passwordsDontMatch': 'Kata laluan tidak sepadan',
    'register.success': 'Akaun berjaya dicipta!',
    'register.failed': 'Gagal mencipta akaun',

    // Dashboard
    'dashboard.title': 'Papan Pemuka ThinkTap',
    'dashboard.welcome': 'Selamat kembali,',
    'dashboard.plan': 'Pelan:',
    'dashboard.upgrade': 'Naik taraf ke Pro',
    'dashboard.signOut': 'Log Keluar',
    'dashboard.totalQuizzes': 'Jumlah Kuiz',
    'dashboard.activeNow': 'Aktif Sekarang',
    'dashboard.completed': 'Selesai',
    'dashboard.create': 'Cipta',
    'dashboard.thinktap': 'ThinkTap',
    'dashboard.thinktapDesc': 'Pelajaran interaktif pendek dengan kuiz.',
    'dashboard.yourQuizzes': 'Kuiz Anda',
    'dashboard.manageQuizzes': 'Urus dan lihat kuiz ThinkTap anda',
    'dashboard.newQuiz': 'Kuiz Baru',
    'dashboard.loading': 'Memuatkan...',
    'dashboard.noQuizzes': 'Belum ada kuiz',
    'dashboard.createFirst': 'Cipta kuiz pertama anda untuk bermula',
    'dashboard.createFirstQuiz': 'Cipta Kuiz Pertama Anda',
    'dashboard.questions': 'Soalan:',
    'dashboard.sessions': 'Sesi:',
    'dashboard.updated': 'Dikemaskini:',
    'dashboard.hostLive': 'Hos secara langsung',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Padam',
    'dashboard.deleteConfirm': 'Adakah anda pasti mahu memadam kuiz ini? Tindakan ini tidak boleh dibatalkan.',
    'dashboard.failedLoad': 'Gagal memuatkan kuiz',
    'dashboard.viewReports': 'Lihat Laporan',
    'dashboard.untitledQuiz': 'Kuiz Tanpa Tajuk',

    // Reports
    'reports.title': 'Laporan',
    'reports.subtitle': 'Lihat dan urus sesi kuiz yang telah selesai',
    'reports.sidebarAll': 'Semua laporan',
    'reports.sidebarTrash': 'Tong sampah',
    'reports.headerAll': 'Semua laporan',
    'reports.headerTrash': 'Tong sampah',
    'reports.searchPlaceholder': 'Cari',
    'reports.selectAll': 'Pilih semua',
    'reports.sortBy': 'Isih ikut:',
    'reports.sort.dateDesc': 'Tarikh (Terbaru dahulu)',
    'reports.sort.dateAsc': 'Tarikh (Terdahulu dahulu)',
    'reports.sort.titleAsc': 'Tajuk (A-Z)',
    'reports.sort.titleDesc': 'Tajuk (Z-A)',
    'reports.emptyAll': 'Belum ada laporan',
    'reports.emptyTrash': 'Tong sampah kosong',
    'reports.loadError': 'Gagal memuatkan laporan',
    'reports.moveToTrashSuccess': 'Laporan dipindahkan ke tong sampah',
    'reports.moveToTrashError': 'Gagal memindahkan laporan ke tong sampah',
    'reports.restoreSuccess': 'Laporan dipulihkan',
    'reports.restoreError': 'Gagal memulihkan laporan',
    'reports.permanentDeleteConfirm':
      'Anda pasti mahu memadam laporan ini secara kekal? Tindakan ini tidak boleh dibuat asal.',
    'reports.permanentDeleteSuccess': 'Laporan dipadam secara kekal',
    'reports.permanentDeleteError': 'Gagal memadam laporan',
    'reports.bulkMoveLabel': 'Pindahkan pilihan ke Tong sampah',
    'reports.bulkMoveSuccess': 'Laporan terpilih dipindahkan ke tong sampah',
    'reports.bulkMoveError': 'Gagal memindahkan laporan terpilih ke tong sampah',
    'reports.bulkRestoreLabel': 'Pulihkan pilihan',
    'reports.bulkRestoreSuccess': 'Laporan terpilih dipulihkan',
    'reports.bulkRestoreError': 'Gagal memulihkan laporan terpilih',
    'reports.bulkPermanentDeleteLabel': 'Padam kekal pilihan',
    'reports.bulkPermanentDeleteSuccess': 'Laporan terpilih dipadam secara kekal',
    'reports.bulkPermanentDeleteError': 'Gagal memadam kekal laporan terpilih',
    'reports.badgeFinished': 'Selesai',
    'reports.endedLabel': 'Tamat {date}',
    'reports.participantsLabel': 'Peserta',
    'reports.menu.viewQuestions': 'Lihat Soalan',
    'reports.menu.viewParticipants': 'Lihat Peserta',
    'reports.menu.viewInsights': 'Lihat Insight',
    'reports.menu.moveToTrash': 'Pindah ke Tong',
    'reports.menu.restore': 'Pulihkan',
    'reports.menu.permanentlyDelete': 'Padam Kekal',
    'reports.participants.title': 'Peserta',
    'reports.participants.allCount': 'Semua ({count})',
    'reports.participants.searchPlaceholder': 'Cari',
    'reports.participants.empty': 'Tiada peserta ditemui',
    'reports.participants.col.nickname': 'Nama gelaran',
    'reports.participants.col.rank': 'Kedudukan',
    'reports.participants.col.correct': 'Jawapan betul',
    'reports.participants.col.unanswered': 'Tidak dijawab',
    'reports.participants.col.score': 'Skor akhir',
    'reports.questions.title': 'Soalan',
    'reports.questions.all': 'Semua ({count})',
    'reports.questions.difficult': 'Soalan sukar ({count})',
    'reports.questions.searchPlaceholder': 'Cari',
    'reports.questions.empty': 'Tiada soalan ditemui',
    'reports.questions.col.question': 'Soalan',
    'reports.questions.col.type': 'Jenis',
    'reports.questions.col.correctIncorrect': 'Betul / Salah',

    // Host
    'host.title': 'Hos ThinkTap',
    'host.description': 'Apabila anda menekan mula, lobi berwarna-warni akan terbuka dengan PIN permainan dan kod QR supaya pelajar boleh menyertai.',
    'host.start': 'Mula',

    // Session Join
    'joinSession.title': 'Sertai Sesi',
    'joinSession.subtitle': 'Masukkan kod 6 digit yang diberikan oleh pensyarah anda',
    'joinSession.digitsEntered': 'digit dimasukkan',
    'joinSession.joining': 'Menyertai...',
    'joinSession.join': 'Sertai Sesi',
    'joinSession.clear': 'Kosongkan',
    'joinSession.noCode': 'Tiada kod? Tanya pensyarah anda atau',
    'joinSession.signInLecturer': 'log masuk sebagai pensyarah',
    'joinSession.invalidCode': 'Sila masukkan kod 6 digit yang sah',
    'joinSession.sessionFound': 'Sesi ditemui! Masukkan nama panggilan anda untuk menyertai.',
    'joinSession.invalidCodeError': 'Kod sesi tidak sah',

    // Join Specific Session
    'joinSpecific.title': 'Sertai Kuiz',
    'joinSpecific.subtitle': 'Masukkan nama panggilan untuk menyertai kuiz ini.',
    'joinSpecific.duplicateNickname': 'Nama panggilan ini sudah digunakan dalam kuiz ini. Sila pilih yang lain.',
    'joinSpecific.nickname': 'Nama Panggilan',
    'joinSpecific.nicknamePlaceholder': 'Taip nama panggilan anda',
    'joinSpecific.join': 'Sertai',
    'joinSpecific.recognizeNickname': 'Pastikan anda mengenali nama panggilan anda pada skrin hos.',

    // Waiting
    'waiting.youreIn': 'Anda sudah masuk!',
    'waiting.seeNickname': 'Adakah anda melihat nama panggilan anda di skrin?',
    'waiting.yourNickname': 'Nama panggilan anda',
    'waiting.waiting': 'Menunggu...',
    'waiting.waitLecturer': 'Sila tunggu pensyarah anda memulakan kuiz.',
    'waiting.getReady': 'Bersedia!',
    'waiting.quizStarting': 'Kuiz akan bermula tidak lama lagi...',

    // Participant
    'participant.submit': 'Hantar',
    'participant.selectAnswer': 'Sila pilih jawapan',
    'participant.selectAtLeastOne': 'Sila pilih sekurang-kurangnya satu jawapan',
    'participant.responseSubmitted': 'Jawapan dihantar!',
    'participant.failedSubmit': 'Gagal menghantar jawapan',
    'participant.timeRemaining': 'Masa Tinggal',
    'participant.waitingQuestion': 'Menunggu soalan seterusnya...',
    'participant.sessionEnded': 'Sesi Tamat',
    'participant.yourResults': 'Keputusan Anda',
    'participant.rank': 'Kedudukan',
    'participant.points': 'Mata',
    'participant.accuracy': 'Ketepatan',
    'participant.correct': 'Betul',
    'participant.incorrect': 'Salah',
    'participant.totalQuestions': 'Jumlah Soalan',
    'participant.totalResponses': 'Jumlah Jawapan',
    'participant.failedLoad': 'Gagal memuatkan sesi',
    'participant.failedLoadResults': 'Gagal memuatkan keputusan anda',
    'participant.getReady': 'Bersedia!',
    'participant.quizStarting': 'Kuiz akan bermula tidak lama lagi...',
    'participant.sessionCompleteTitle': 'Sesi Tamat!',
    'participant.greatJobWithName': 'Tahniah, {name}!',
    'participant.greatJob': 'Tahniah!',
    'participant.rankOf': 'Kedudukan #{rank}',
    'participant.outOfParticipants': 'Daripada {count} peserta',
    'participant.summary': 'Anda menjawab {responses} daripada {questions} soalan',

    // Quiz Builder
    'builder.back': 'Kembali',
    'builder.titlePlaceholder': 'Masukkan tajuk ThinkTap...',
    'builder.thinktapDesc': 'Pelajaran interaktif pendek dengan kuiz.',
    'builder.saving': 'Menyimpan...',
    'builder.save': 'Simpan',
    'builder.quiz': 'Kuiz',
    'builder.questionsInQuiz': 'Soalan dalam kuiz ini',
    'builder.noQuestions': 'Belum ada soalan. Gunakan editor di sebelah kanan, kemudian tekan',
    'builder.saveButton': 'Simpan',
    'builder.add': '+ Tambah',
    'builder.quizQuestion': 'Soalan kuiz',
    'builder.questionPlaceholder': 'Mula menaip soalan anda',
    'builder.addAnswer': 'Tambah lebih banyak jawapan',
    'builder.questionType': 'Jenis soalan',
    'builder.mcSingle': 'Pilihan berganda • Pilih satu',
    'builder.mcMulti': 'Pilihan berganda • Pilih banyak',
    'builder.trueFalse': 'Betul / Salah',
    'builder.timeLimit': 'Had masa (saat)',
    'builder.points': 'Mata',
    'builder.standard': 'Standard',
    'builder.double': 'Mata berganda',
    'builder.goToOverview': 'Pergi ke gambaran keseluruhan kuiz',
    'builder.enterQuestion': 'Sila masukkan soalan',
    'builder.atLeastTwoOptions': 'Sila berikan sekurang-kurangnya dua pilihan jawapan',
    'builder.markCorrectAnswer': 'Sila tandakan sekurang-kurangnya satu jawapan yang betul',
    'builder.selectCorrectAnswer': 'Sila pilih jawapan yang betul',
    'builder.selectAtLeastOneCorrect': 'Sila pilih sekurang-kurangnya satu jawapan yang betul',
    'builder.questionSaved': 'Soalan disimpan',
    'builder.failedAddQuestion': 'Gagal menambah soalan',
    'builder.removeQuestion': 'Buang soalan ini dari kuiz?',
    'builder.failedRemove': 'Gagal membuang soalan',
    'builder.untitledQuestion': 'Soalan tanpa tajuk',
    'builder.multipleChoice': 'Pilihan berganda',
    'builder.trueFalseLabel': 'Betul / Salah',
    'builder.question': 'Soalan',
    'builder.pts': 'mata',
    'builder.addAnswerPlaceholder': 'Tambah jawapan',
    'builder.optional': '(pilihan)',
    'builder.quizSettings': 'Tetapan kuiz',
    'builder.enableMusic': 'Aktifkan muzik latar (hanya pensyarah)',
    'builder.musicTrack': 'Nama fail muzik',
    'builder.musicTrackJumanji': 'Dram Jumanji (Lalai)',
    'builder.musicTrackLofi': 'Lo-fi santai',
    'builder.musicTrackEnergetic': 'Rentak bertenaga',
    'builder.musicTrackCalm': 'Piano menenangkan',
    'builder.enableCountdown': 'Aktifkan kiraan detik 5 saat sebelum soalan pertama',
    'builder.enablePodium': 'Tunjukkan podium pada akhir sesi',

    // Lecturer Session
    'lecturer.startSession': 'Mula Sesi',
    'lecturer.endSession': 'Tamatkan Sesi',
    'lecturer.sessionCode': 'Kod Sesi',
    'lecturer.copyCode': 'Salin Kod',
    'lecturer.codeCopied': 'Kod sesi disalin!',
    'lecturer.participants': 'Peserta',
    'lecturer.noParticipants': 'Belum ada peserta',
    'lecturer.addQuestion': 'Tambah Soalan',
    'lecturer.startQuestion': 'Mula Soalan',
    'lecturer.endQuestion': 'Tamatkan Soalan',
    'lecturer.showResults': 'Tunjukkan Keputusan',
    'lecturer.hideResults': 'Sembunyikan Keputusan',
    'lecturer.viewInsights': 'Lihat Wawasan',
    'lecturer.leaderboard': 'Papan Pendahulu',
    'lecturer.questionStarted': 'Soalan dimulakan!',
    'lecturer.sessionStarted': 'Sesi dimulakan!',
    'lecturer.failedStart': 'Gagal memulakan sesi',
    'lecturer.failedLoad': 'Gagal memuatkan sesi',
    'lecturer.failedLoadQuestions': 'Gagal memuatkan soalan',
    'lecturer.noQuestions': 'Tiada soalan tersedia. Tambah soalan dalam pembina kuiz.',
    'lecturer.waitingParticipants': 'Menunggu peserta...',
    'lecturer.questionActive': 'Soalan Aktif',
    'lecturer.resultsShown': 'Keputusan Ditunjukkan',
    'lecturer.sessionEnded': 'Sesi Tamat',
    'lecturer.getReady': 'Bersedia!',
    'lecturer.quizStarting': 'Kuiz akan bermula tidak lama lagi...',
    'lecturer.back': 'Kembali',
    'lecturer.connected': 'Disambungkan',

    // Join Session
    'join.title': 'Sertai Sesi',
    'join.description': 'Masukkan kod 6 digit yang diberikan oleh pensyarah anda',
    'join.button': 'Sertai Sesi',
    'join.joining': 'Menyertai...',
    'join.clear': 'Kosongkan',
    'join.digitsEntered': '{count}/6 digit dimasukkan',
    'join.invalidCode': 'Sila masukkan kod 6 digit yang sah',
    'join.sessionFound': 'Sesi dijumpai! Masukkan nama samaran anda untuk menyertai.',
    'join.noCode': 'Tiada kod? Tanya pensyarah anda atau',
    'join.signInAsLecturer': 'log masuk sebagai pensyarah',
    'lecturer.disconnected': 'Terputus',
    'lecturer.participant': 'peserta',
    'lecturer.gamePin': 'PIN Permainan',
    'lecturer.qrCodeAlt': 'Kod QR sertai kuiz',
    'lecturer.qrCodeInstructions': 'Pelajar boleh mengimbas kod QR atau melayari https://thinktap.link/session/join untuk memasukkan PIN dan nama samaran.',
    'lecturer.firstQuestionStarting': 'Soalan pertama akan bermula tidak lama lagi...',
    'lecturer.nextQuestion': 'Soalan Seterusnya',
    'lecturer.finishSession': 'Tamatkan Sesi',
    'lecturer.results': 'Keputusan',
    'lecturer.totalResponses': 'Jumlah Jawapan',
    'lecturer.correct': 'Betul',
    'lecturer.accuracy': 'Ketepatan',
    'lecturer.readyToStart': 'Bersedia untuk mula',
    'lecturer.question': 'soalan',
    'lecturer.questions': 'soalan',
    'lecturer.ready': 'sedia',
    'lecturer.connecting': 'Menyambung ke sesi...',
    'lecturer.loadingQuestions': 'Memuatkan soalan...',
    'lecturer.startFirstQuestion': 'Mulakan Soalan Pertama',
    'lecturer.participantJoined': 'peserta telah menyertai',
    'lecturer.participantsJoined': 'peserta telah menyertai',
    'lecturer.sessionComplete': 'Sesi Selesai!',
    'lecturer.topPerformers': '3 Peserta Teratas',
    'lecturer.noRankingsAvailable': 'Kedudukan belum tersedia',
    'lecturer.backToDashboard': 'Kembali ke Papan Pemuka',
    'lecturer.failedEndSession': 'Gagal menamatkan sesi',
    'lecturer.notConnected': 'Tidak disambungkan. Sila tunggu...',
    'lecturer.rankingsLoadWarning': 'Tidak dapat memuatkan kedudukan, tetapi sesi telah berjaya ditamatkan',
    'lecturer.statusCreated': 'Dicipta',
    'lecturer.statusActive': 'Aktif',
    'lecturer.statusEnded': 'Ditamatkan',
    'lecturer.modeRush': 'Mod Rush',
    'lecturer.modeThinking': 'Mod Berfikir',
    'lecturer.modeSeminar': 'Mod Seminar',

    // Common
    'common.loading': 'Memuatkan...',
    'common.back': 'Kembali',
    'common.error': 'Ralat',
    'common.success': 'Berjaya',
    'common.cancel': 'Batal',
    'common.confirm': 'Sahkan',
    'common.save': 'Simpan',
    'common.delete': 'Padam',
    'common.edit': 'Edit',
    'common.close': 'Tutup',
  },
  ja: {
    // Navigation
    'nav.features': '機能',
    'nav.howItWorks': '使い方',
    'nav.pricing': '料金',
    'nav.faq': 'よくある質問',
    'nav.login': 'ログイン',
    'nav.register': '無料で始める',

    // Hero/Landing
    'hero.badge': '大学向けに設計',
    'hero.title': 'リアルタイム参加で\n教室を変革する',
    'hero.subtitle':
      'ThinkTap はリアルタイムクイズや即時フィードバック、強力な分析機能でインタラクティブな学習を実現します。',
    'hero.ctaPrimary': '無料で始める',
    'hero.ctaSecondary': 'デモを見る',
    'hero.note': 'クレジットカード不要 • 2 分でセットアップ • ずっと無料プランあり',

    // Landing Page - Features
    'landing.features.title': 'エンゲージメントに必要なすべて',
    'landing.features.subtitle': '現代の教室環境向けに特別に設計された強力な機能',
    'landing.features.realTime.title': 'リアルタイムインタラクション',
    'landing.features.realTime.desc': 'Rush、Thinking、Seminarモードでライブクイズを実行。学生は任意のデバイスからリアルタイムで回答します。',
    'landing.features.questionFormats.title': '多様な質問形式',
    'landing.features.questionFormats.desc': '多肢選択、正誤、複数選択、短答・長答問題。すべてを1つのプラットフォームに統合。',
    'landing.features.insights.title': '実用的なインサイト',
    'landing.features.insights.desc': '美しいチャートとグラフで応答率、正確率、学生のエンゲージメントを確認できます。',
    'landing.features.everywhere.title': 'どこでも利用可能',
    'landing.features.everywhere.desc': '講師と学生向けのWebおよびモバイルアプリ。簡単な6桁コードでセッションに参加。',
    'landing.features.privacy.title': 'プライバシーファーストの学習',
    'landing.features.privacy.desc': 'Seminarモードは、敏感なトピックやオープンな議論のために匿名の回答を可能にします。',
    'landing.features.easy.title': '使いやすい',
    'landing.features.easy.desc': '数秒でセッションを作成して開始。学生はアカウントなしで即座に参加できます。',

    // Landing Page - How It Works
    'landing.howItWorks.title': '使い方',
    'landing.howItWorks.subtitle': '3つの簡単なステップで始められます',
    'landing.howItWorks.step1.title': 'セッションを作成',
    'landing.howItWorks.step1.desc': '質問モードを選択し、数秒で質問を作成',
    'landing.howItWorks.step2.title': '学生が参加',
    'landing.howItWorks.step2.desc': '6桁コードを共有。学生は任意のデバイスから即座に参加',
    'landing.howItWorks.step3.title': 'エンゲージ＆分析',
    'landing.howItWorks.step3.desc': 'ライブ質問を実行し、リアルタイムの応答を確認し、インサイトをレビュー',

    // Landing Page - Pricing
    'landing.pricing.title': 'シンプルで透明性のある料金',
    'landing.pricing.subtitle': 'ニーズに合ったプランを選択',
    'landing.pricing.freemium.title': 'Freemium',
    'landing.pricing.freemium.price': 'RM0',
    'landing.pricing.freemium.period': '/月',
    'landing.pricing.freemium.unlimited': '無制限のライブセッション',
    'landing.pricing.freemium.allTypes': 'すべての質問タイプ',
    'landing.pricing.freemium.allModes': 'すべての3モード',
    'landing.pricing.freemium.noHistory': '履歴保存なし',
    'landing.pricing.freemium.cta': '無料で始める',
    'landing.pricing.pro.title': 'ThinkTap Pro',
    'landing.pricing.pro.price': 'RM20',
    'landing.pricing.pro.period': '/月',
    'landing.pricing.pro.badge': '最も人気',
    'landing.pricing.pro.everythingFree': '無料版のすべてを含む',
    'landing.pricing.pro.fullHistory': '完全な履歴',
    'landing.pricing.pro.advanced': '高度な分析',
    'landing.pricing.pro.export': '結果のエクスポート',
    'landing.pricing.pro.cta': '購読',
    'landing.pricing.faculty.title': '教員プラン',
    'landing.pricing.faculty.price': 'RM1K',
    'landing.pricing.faculty.period': '/月',
    'landing.pricing.faculty.everythingPro': 'Pro版のすべてを含む',
    'landing.pricing.faculty.multipleUsers': '複数ユーザー',
    'landing.pricing.faculty.shared': '共有リソース',
    'landing.pricing.faculty.branding': 'カスタムブランディング',
    'landing.pricing.faculty.cta': '営業に連絡',
    'landing.pricing.university.title': '大学',
    'landing.pricing.university.price': 'カスタム',
    'landing.pricing.university.everythingFaculty': '教員版のすべてを含む',
    'landing.pricing.university.unlimitedUsers': '無制限ユーザー',
    'landing.pricing.university.lms': 'LMS統合',
    'landing.pricing.university.onPremise': 'オンプレミスオプション',
    'landing.pricing.university.cta': '営業に連絡',

    // Landing Page - CTA
    'landing.cta.title': '教室を変革する準備はできていますか？',
    'landing.cta.subtitle': 'すでにThinkTapを使用している何百人もの講師に参加してください',
    'landing.cta.button': '無料で始める',
    'landing.cta.note': 'クレジットカード不要 • 2分でセットアップ',

    // Landing Page - Footer
    'landing.footer.description': '大学向けに構築されたインタラクティブな教室エンゲージメントプラットフォーム。',
    'landing.footer.product': '製品',
    'landing.footer.company': '会社',
    'landing.footer.connect': '接続',
    'landing.footer.features': '機能',
    'landing.footer.pricing': '料金',
    'landing.footer.docs': 'ドキュメント',
    'landing.footer.about': 'について',
    'landing.footer.contact': 'お問い合わせ',
    'landing.footer.privacy': 'プライバシー',
    'landing.footer.terms': '利用規約',
    'landing.footer.copyright': '© 2025 ThinkTap. 全著作権所有。',

    // Login
    'login.title': 'ThinkTapへようこそ',
    'login.subtitle': 'アカウントにサインインして続行',
    'login.email': 'メール',
    'login.password': 'パスワード',
    'login.emailPlaceholder': 'lecturer@university.edu',
    'login.forgotPassword': 'パスワードを忘れた場合',
    'login.signingIn': 'サインイン中...',
    'login.signIn': 'サインイン',
    'login.noAccount': 'アカウントをお持ちでない場合',
    'login.signUp': 'サインアップ',
    'login.fillAllFields': 'すべてのフィールドを入力してください',
    'login.invalidCredentials': 'メールまたはパスワードが無効です',
    'login.success': 'ログインに成功しました！',

    // Register
    'register.title': 'アカウントを作成',
    'register.subtitle': 'インタラクティブな学習セッションを作成開始',
    'register.confirmPassword': 'パスワード確認',
    'register.passwordHint': '8文字以上である必要があります',
    'register.terms': 'アカウントを作成することで、',
    'register.termsLink': '利用規約',
    'register.privacyLink': 'プライバシーポリシー',
    'register.and': 'および',
    'register.creating': 'アカウント作成中...',
    'register.createAccount': 'アカウントを作成',
    'register.haveAccount': 'すでにアカウントをお持ちの場合',
    'register.signIn': 'サインイン',
    'register.passwordTooShort': 'パスワードは8文字以上である必要があります',
    'register.passwordsDontMatch': 'パスワードが一致しません',
    'register.success': 'アカウントが正常に作成されました！',
    'register.failed': 'アカウントの作成に失敗しました',

    // Forgot Password
    'forgotPassword.title': 'パスワードを忘れた場合',
    'forgotPassword.subtitle': 'メールアドレスを入力してください。パスワードリセットリンクをお送りします',
    'forgotPassword.fillEmail': 'メールアドレスを入力してください',
    'forgotPassword.sendResetLink': 'リセットリンクを送信',
    'forgotPassword.sending': '送信中...',
    'forgotPassword.success': 'パスワードリセットリンクを送信しました！メールを確認してください',
    'forgotPassword.failed': 'リセットリンクの送信に失敗しました',
    'forgotPassword.checkEmail': 'メールでリセットリンクを確認してください',
    'forgotPassword.emailSent': 'パスワードリセットリンクをメールアドレスに送信しました。受信トレイを確認し、指示に従ってパスワードをリセットしてください。',
    'forgotPassword.backToLogin': 'ログインに戻る',

    // Terms
    'terms.title': '利用規約',
    'terms.lastUpdated': '最終更新',
    'terms.lastUpdatedDate': '2025年1月',
    'terms.section1.title': '1. 規約の承認',
    'terms.section1.content': 'ThinkTapにアクセスして使用することにより、本契約の条項に同意し、それに拘束されることに同意したものとみなされます。本利用規約に同意しない場合は、サービスを使用しないでください。',
    'terms.section2.title': '2. 使用ライセンス',
    'terms.section2.content': 'ThinkTapを個人的、非商業的な一時的な閲覧のために一時的に使用する許可が付与されます。これはライセンスの付与であり、所有権の譲渡ではなく、このライセンスの下で以下を行うことはできません：',
    'terms.section2.point1': '資料を変更または複製する',
    'terms.section2.point2': '資料を商業目的または公的展示のために使用する',
    'terms.section2.point3': 'サービスに含まれるソフトウェアをリバースエンジニアリングしようとする',
    'terms.section2.point4': '資料から著作権またはその他の所有権表記を削除する',
    'terms.section3.title': '3. ユーザーアカウント',
    'terms.section3.content': 'アカウントとパスワードの機密性を維持する責任があります。アカウントまたはパスワードの下で発生するすべての活動について責任を負うことに同意します。',
    'terms.section4.title': '4. ユーザーコンテンツ',
    'terms.section4.content': 'ThinkTap上またはThinkTapを通じて送信、投稿、または表示するコンテンツの所有権を保持します。コンテンツを送信することにより、サービスを提供および改善する目的で、コンテンツを使用、複製、配布するための世界的な非独占的、ロイヤリティフリーのライセンスを当社に付与します。',
    'terms.section5.title': '5. 禁止される使用',
    'terms.section5.content': 'サービスを損傷、無効化、過負荷、または損害を与える、または他の当事者のサービス使用と享受を妨害する方法でThinkTapを使用することはできません。禁止される活動には、スパム、ハラスメント、または違法活動が含まれますが、これに限定されません。',
    'terms.section6.title': '6. 責任の制限',
    'terms.section6.content': 'ThinkTapは、間接的、偶発的、特別、結果的、または懲罰的損害、または利益または収入の損失（直接的または間接的に発生したかどうか）、またはデータ、使用、のれん、またはサービスの使用から生じるその他の無形の損失について責任を負いません。',
    'terms.section7.title': '7. 規約の変更',
    'terms.section7.content': 'いつでもこれらの規約を変更する権利を留保します。このページに新しい利用規約を投稿し、「最終更新」日を更新することにより、ユーザーに変更を通知します。',
    'terms.questions': 'これらの規約について質問がありますか？',
    'terms.contactUs': 'お問い合わせ',

    // Privacy
    'privacy.title': 'プライバシーポリシー',
    'privacy.lastUpdated': '最終更新',
    'privacy.lastUpdatedDate': '2025年1月',
    'privacy.section1.title': '1. 収集する情報',
    'privacy.section1.content': 'アカウントの作成、サービスの使用、またはお問い合わせの際に直接提供していただく情報を収集します。これには、メールアドレス、お名前、ThinkTapを通じて作成または共有するコンテンツが含まれる場合があります。',
    'privacy.section2.title': '2. 情報の使用方法',
    'privacy.section2.content': '収集した情報を次の目的で使用します：',
    'privacy.section2.point1': 'サービスの提供、維持、改善',
    'privacy.section2.point2': '取引の処理と関連情報の送信',
    'privacy.section2.point3': '技術通知とサポートメッセージの送信',
    'privacy.section2.point4': 'コメントと質問への対応',
    'privacy.section3.title': '3. 情報の共有',
    'privacy.section3.content': '同意なく、個人情報を第三者に販売、取引、またはその他の方法で譲渡することはありません。ただし、このポリシーに記載されている場合を除きます。サービスの運営、事業の遂行、またはユーザーへのサービス提供を支援するサービスプロバイダーと情報を共有する場合があります。',
    'privacy.section4.title': '4. データセキュリティ',
    'privacy.section4.content': '個人情報を不正アクセス、改ざん、開示、または破壊から保護するために、適切な技術的および組織的な対策を実施しています。ただし、インターネット経由の送信方法は100%安全ではありません。',
    'privacy.section5.title': '5. お客様の権利',
    'privacy.section5.content': 'いつでも個人情報にアクセス、更新、または削除する権利があります。アカウント設定から、または直接お問い合わせいただくことでこれを行うことができます。',
    'privacy.section6.title': '6. Cookie',
    'privacy.section6.content': 'サービス上のアクティビティを追跡し、特定の情報を保持するためにCookieと同様の追跡テクノロジーを使用しています。ブラウザにすべてのCookieを拒否するか、Cookieが送信されるときに通知するように指示できます。',
    'privacy.section7.title': '7. プライバシーポリシーの変更',
    'privacy.section7.content': 'プライバシーポリシーを随時更新する場合があります。このページに新しいプライバシーポリシーを投稿し、「最終更新」日を更新することにより、変更を通知します。',
    'privacy.questions': 'プライバシー慣行について質問がありますか？',
    'privacy.contactUs': 'お問い合わせ',

    // FAQ
    'faq.title': 'よくある質問',
    'faq.subtitle': 'ThinkTapに関するよくある質問の回答を見つける',
    'faq.q1.question': 'ThinkTapとは何ですか？',
    'faq.q1.answer': 'ThinkTapは、大学や教育機関向けに設計されたインタラクティブな学習プラットフォームです。講師が学生とリアルタイムのクイズやインタラクティブなセッションを作成および開催できるようにします。',
    'faq.q2.question': '学生はどのようにセッションに参加しますか？',
    'faq.q2.answer': '学生は講師が提供する6桁のセッションコードを入力してセッションに参加できます。学生が参加するためにアカウントは必要ありません。',
    'faq.q3.question': 'どのような問題タイプがサポートされていますか？',
    'faq.q3.answer': 'ThinkTapは、複数選択（単一選択と複数選択）、真/偽、短答、長答問題など、複数の問題タイプをサポートしています。',
    'faq.q4.question': 'ThinkTapは無料で使用できますか？',
    'faq.q4.answer': 'はい！ThinkTapは、無制限のライブセッションとすべての問題タイプへのアクセスを備えた無料プランを提供しています。完全な履歴、高度な分析、エクスポート機能などの高度な機能については、プレミアムプランが利用できます。',
    'faq.q5.question': 'モバイルデバイスでThinkTapを使用できますか？',
    'faq.q5.answer': 'はい、ThinkTapは完全にレスポンシブで、スマートフォンやタブレットを含むすべてのデバイスで動作します。講師と学生の両方が、Webブラウザを備えた任意のデバイスからThinkTapを使用できます。',
    'faq.q6.question': 'スコアリングシステムはどのように機能しますか？',
    'faq.q6.answer': 'ThinkTapは、正確性、応答時間、ストリークボーナスを考慮した包括的なスコアリングシステムを使用しています。より速く、より正確な応答は、より高いスコアを受け取ります。',
    'faq.q7.question': 'セッションは匿名にできますか？',
    'faq.q7.answer': 'はい、ThinkTapは匿名の応答を可能にするセミナーモードを提供しており、学生がより快適に参加できる可能性のある敏感なトピックやオープンディスカッションに最適です。',
    'faq.q8.question': 'サポートを受けるにはどうすればよいですか？',
    'faq.q8.answer': 'お問い合わせページからサポートチームに連絡するか、support@thinktap.comにメールでお問い合わせください。ThinkTapを最大限に活用できるようお手伝いします。',
    'faq.stillHaveQuestions': 'まだ質問がありますか？',
    'faq.contactUs': 'お問い合わせ',

    // Dashboard
    'dashboard.title': 'ThinkTapダッシュボード',
    'dashboard.welcome': 'おかえりなさい、',
    'dashboard.plan': 'プラン：',
    'dashboard.upgrade': 'Proにアップグレード',
    'dashboard.signOut': 'サインアウト',
    'dashboard.totalQuizzes': 'クイズ総数',
    'dashboard.activeNow': '現在アクティブ',
    'dashboard.completed': '完了',
    'dashboard.create': '作成',
    'dashboard.thinktap': 'ThinkTap',
    'dashboard.thinktapDesc': 'クイズ付きの短いインタラクティブレッスン。',
    'dashboard.yourQuizzes': 'あなたのクイズ',
    'dashboard.manageQuizzes': 'ThinkTapクイズを管理および表示',
    'dashboard.newQuiz': '新しいクイズ',
    'dashboard.loading': '読み込み中...',
    'dashboard.noQuizzes': 'まだクイズがありません',
    'dashboard.createFirst': '最初のクイズを作成して始めましょう',
    'dashboard.createFirstQuiz': '最初のクイズを作成',
    'dashboard.questions': '質問：',
    'dashboard.sessions': 'セッション：',
    'dashboard.updated': '更新：',
    'dashboard.hostLive': 'ライブでホスト',
    'dashboard.edit': '編集',
    'dashboard.delete': '削除',
    'dashboard.deleteConfirm': 'このクイズを削除してもよろしいですか？この操作は元に戻せません。',
    'dashboard.failedLoad': 'クイズの読み込みに失敗しました',
    'dashboard.viewReports': 'レポートを表示',
    'dashboard.untitledQuiz': 'タイトルなしのクイズ',

    // Reports
    'reports.title': 'レポート',
    'reports.subtitle': '完了したクイズセッションを表示・管理します',
    'reports.sidebarAll': 'すべてのレポート',
    'reports.sidebarTrash': 'ゴミ箱',
    'reports.headerAll': 'すべてのレポート',
    'reports.headerTrash': 'ゴミ箱',
    'reports.searchPlaceholder': '検索',
    'reports.selectAll': 'すべて選択',
    'reports.sortBy': '並び替え:',
    'reports.sort.dateDesc': '日付（新しい順）',
    'reports.sort.dateAsc': '日付（古い順）',
    'reports.sort.titleAsc': 'タイトル（A-Z）',
    'reports.sort.titleDesc': 'タイトル（Z-A）',
    'reports.emptyAll': 'まだレポートがありません',
    'reports.emptyTrash': 'ゴミ箱は空です',
    'reports.loadError': 'レポートの読み込みに失敗しました',
    'reports.moveToTrashSuccess': 'レポートをゴミ箱に移動しました',
    'reports.moveToTrashError': 'レポートをゴミ箱に移動できませんでした',
    'reports.restoreSuccess': 'レポートを復元しました',
    'reports.restoreError': 'レポートの復元に失敗しました',
    'reports.permanentDeleteConfirm':
      'このレポートを完全に削除してもよろしいですか？この操作は元に戻せません。',
    'reports.permanentDeleteSuccess': 'レポートを完全に削除しました',
    'reports.permanentDeleteError': 'レポートの削除に失敗しました',
    'reports.bulkMoveLabel': '選択したものをゴミ箱へ移動',
    'reports.bulkMoveSuccess': '選択したレポートをゴミ箱に移動しました',
    'reports.bulkMoveError': '選択したレポートをゴミ箱に移動できませんでした',
    'reports.bulkRestoreLabel': '選択したものを復元',
    'reports.bulkRestoreSuccess': '選択したレポートを復元しました',
    'reports.bulkRestoreError': '選択したレポートを復元できませんでした',
    'reports.bulkPermanentDeleteLabel': '選択したものを完全に削除',
    'reports.bulkPermanentDeleteSuccess': '選択したレポートを完全に削除しました',
    'reports.bulkPermanentDeleteError': '選択したレポートを完全に削除できませんでした',
    'reports.badgeFinished': '完了',
    'reports.endedLabel': '{date} に終了',
    'reports.participantsLabel': '参加者',
    'reports.menu.viewQuestions': '質問を表示',
    'reports.menu.viewParticipants': '参加者を表示',
    'reports.menu.viewInsights': 'インサイトを表示',
    'reports.menu.moveToTrash': 'ゴミ箱に移動',
    'reports.menu.restore': '復元',
    'reports.menu.permanentlyDelete': '完全に削除',
    'reports.participants.title': '参加者',
    'reports.participants.allCount': 'すべて（{count}）',
    'reports.participants.searchPlaceholder': '検索',
    'reports.participants.empty': '参加者が見つかりません',
    'reports.participants.col.nickname': 'ニックネーム',
    'reports.participants.col.rank': '順位',
    'reports.participants.col.correct': '正解数',
    'reports.participants.col.unanswered': '未回答',
    'reports.participants.col.score': '最終スコア',
    'reports.questions.title': '質問',
    'reports.questions.all': 'すべて（{count}）',
    'reports.questions.difficult': '難しい質問（{count}）',
    'reports.questions.searchPlaceholder': '検索',
    'reports.questions.empty': '質問が見つかりません',
    'reports.questions.col.question': '質問',
    'reports.questions.col.type': 'タイプ',
    'reports.questions.col.correctIncorrect': '正解 / 不正解',

    // Host
    'host.title': 'ThinkTapをホスト',
    'host.description': '開始を押すと、ゲームPINとQRコードが表示されたカラフルなロビーが開き、学生が参加できるようになります。',
    'host.start': '開始',

    // Session Join
    'joinSession.title': 'セッションに参加',
    'joinSession.subtitle': '講師から提供された6桁のコードを入力',
    'joinSession.digitsEntered': '桁入力済み',
    'joinSession.joining': '参加中...',
    'joinSession.join': 'セッションに参加',
    'joinSession.clear': 'クリア',
    'joinSession.noCode': 'コードをお持ちでない場合、講師に尋ねるか、',
    'joinSession.signInLecturer': '講師としてサインイン',
    'joinSession.invalidCode': '有効な6桁のコードを入力してください',
    'joinSession.sessionFound': 'セッションが見つかりました！ニックネームを入力して参加してください。',
    'joinSession.invalidCodeError': '無効なセッションコード',

    // Join Specific Session
    'joinSpecific.title': 'クイズに参加',
    'joinSpecific.subtitle': 'このクイズに参加するにはニックネームを入力してください。',
    'joinSpecific.duplicateNickname': 'このニックネームは既にこのクイズで使用されています。別のものを選択してください。',
    'joinSpecific.nickname': 'ニックネーム',
    'joinSpecific.nicknamePlaceholder': 'ニックネームを入力',
    'joinSpecific.join': '参加',
    'joinSpecific.recognizeNickname': 'ホスト画面でニックネームを認識できることを確認してください。',

    // Waiting
    'waiting.youreIn': '参加しました！',
    'waiting.seeNickname': '画面上でニックネームを確認できましたか？',
    'waiting.yourNickname': 'あなたのニックネーム',
    'waiting.waiting': '待機中...',
    'waiting.waitLecturer': '講師がクイズを開始するまでお待ちください。',
    'waiting.getReady': '準備してください！',
    'waiting.quizStarting': 'クイズがまもなく開始されます...',

    // Participant
    'participant.submit': '送信',
    'participant.selectAnswer': '回答を選択してください',
    'participant.selectAtLeastOne': '少なくとも1つの回答を選択してください',
    'participant.responseSubmitted': '回答が送信されました！',
    'participant.failedSubmit': '回答の送信に失敗しました',
    'participant.timeRemaining': '残り時間',
    'participant.waitingQuestion': '次の質問を待っています...',
    'participant.sessionEnded': 'セッション終了',
    'participant.yourResults': 'あなたの結果',
    'participant.rank': 'ランク',
    'participant.points': 'ポイント',
    'participant.accuracy': '正確性',
    'participant.correct': '正解',
    'participant.incorrect': '不正解',
    'participant.totalQuestions': '質問総数',
    'participant.totalResponses': '回答総数',
    'participant.failedLoad': 'セッションの読み込みに失敗しました',
    'participant.failedLoadResults': '結果の読み込みに失敗しました',
    'participant.getReady': '準備してください！',
    'participant.quizStarting': 'クイズがまもなく開始されます...',
    'participant.sessionCompleteTitle': 'セッション完了！',
    'participant.greatJobWithName': '{name}さん、お疲れさまでした！',
    'participant.greatJob': 'お疲れさまでした！',
    'participant.rankOf': '第{rank}位',
    'participant.outOfParticipants': '{count}人中',
    'participant.summary': '{questions}問中{responses}問に回答しました',

    // Quiz Builder
    'builder.back': '戻る',
    'builder.titlePlaceholder': 'ThinkTapタイトルを入力...',
    'builder.thinktapDesc': 'クイズ付きの短いインタラクティブレッスン。',
    'builder.saving': '保存中...',
    'builder.save': '保存',
    'builder.quiz': 'クイズ',
    'builder.questionsInQuiz': 'このクイズの質問',
    'builder.noQuestions': 'まだ質問がありません。右側のエディタを使用し、次に',
    'builder.saveButton': '保存',
    'builder.add': '+ 追加',
    'builder.quizQuestion': 'クイズの質問',
    'builder.questionPlaceholder': '質問の入力を開始',
    'builder.addAnswer': 'さらに回答を追加',
    'builder.questionType': '質問タイプ',
    'builder.mcSingle': '多肢選択 • 単一選択',
    'builder.mcMulti': '多肢選択 • 複数選択',
    'builder.trueFalse': '正誤',
    'builder.timeLimit': '制限時間（秒）',
    'builder.points': 'ポイント',
    'builder.standard': '標準',
    'builder.double': 'ダブルポイント',
    'builder.goToOverview': 'クイズの概要に移動',
    'builder.enterQuestion': '質問を入力してください',
    'builder.atLeastTwoOptions': '少なくとも2つの回答オプションを提供してください',
    'builder.markCorrectAnswer': '少なくとも1つの正解をマークしてください',
    'builder.selectCorrectAnswer': '正解を選択してください',
    'builder.selectAtLeastOneCorrect': '少なくとも1つの正解を選択してください',
    'builder.questionSaved': '質問が保存されました',
    'builder.failedAddQuestion': '質問の追加に失敗しました',
    'builder.removeQuestion': 'この質問をクイズから削除しますか？',
    'builder.failedRemove': '質問の削除に失敗しました',
    'builder.untitledQuestion': 'タイトルなしの質問',
    'builder.multipleChoice': '多肢選択',
    'builder.trueFalseLabel': '正誤',
    'builder.question': '質問',
    'builder.pts': 'ポイント',
    'builder.addAnswerPlaceholder': '回答を追加',
    'builder.optional': '（オプション）',

    // Lecturer Session
    'lecturer.startSession': 'セッションを開始',
    'lecturer.endSession': 'セッションを終了',
    'lecturer.sessionCode': 'セッションコード',
    'lecturer.copyCode': 'コードをコピー',
    'lecturer.codeCopied': 'セッションコードがコピーされました！',
    'lecturer.participants': '参加者',
    'lecturer.noParticipants': 'まだ参加者はいません',
    'lecturer.addQuestion': '質問を追加',
    'lecturer.startQuestion': '質問を開始',
    'lecturer.endQuestion': '質問を終了',
    'lecturer.showResults': '結果を表示',
    'lecturer.hideResults': '結果を非表示',
    'lecturer.viewInsights': 'インサイトを表示',
    'lecturer.leaderboard': 'リーダーボード',
    'lecturer.questionStarted': '質問が開始されました！',
    'lecturer.sessionStarted': 'セッションが開始されました！',
    'lecturer.failedStart': 'セッションの開始に失敗しました',
    'lecturer.failedLoad': 'セッションの読み込みに失敗しました',
    'lecturer.failedLoadQuestions': '質問の読み込みに失敗しました',
    'lecturer.noQuestions': '利用可能な質問がありません。クイズビルダーで質問を追加してください。',
    'lecturer.waitingParticipants': '参加者を待っています...',
    'lecturer.questionActive': '質問アクティブ',
    'lecturer.resultsShown': '結果表示済み',
    'lecturer.sessionEnded': 'セッション終了',
    'lecturer.getReady': '準備してください！',
    'lecturer.quizStarting': 'クイズがまもなく開始されます...',
    'lecturer.statusCreated': '作成済み',
    'lecturer.statusActive': 'アクティブ',
    'lecturer.statusEnded': '終了',
    'lecturer.modeRush': 'ラッシュモード',
    'lecturer.modeThinking': 'シンキングモード',
    'lecturer.modeSeminar': 'セミナーモード',
    'lecturer.gamePin': 'ゲーム PIN',
    'lecturer.qrCodeAlt': 'クイズ参加QRコード',
    'lecturer.qrCodeInstructions': '学生はQRコードをスキャンするか、https://thinktap.link/session/join にアクセスしてPINとニックネームを入力できます。',
    'lecturer.firstQuestionStarting': '最初の問題がまもなく開始されます...',
    'lecturer.readyToStart': '開始の準備ができました',
    'lecturer.question': '質問',
    'lecturer.questions': '質問',
    'lecturer.ready': '準備完了',
    'lecturer.startFirstQuestion': '最初の問題を開始',

    // Join Session
    'join.title': 'セッションに参加',
    'join.description': '講師から提供された6桁のコードを入力してください',
    'join.button': 'セッションに参加',
    'join.joining': '参加中...',
    'join.clear': 'クリア',
    'join.digitsEntered': '{count}/6 桁入力済み',
    'join.invalidCode': '有効な6桁のコードを入力してください',
    'join.sessionFound': 'セッションが見つかりました！ニックネームを入力して参加してください。',
    'join.noCode': 'コードをお持ちでない場合は、講師に尋ねるか、',
    'join.signInAsLecturer': '講師としてログイン',

    // Common
    'common.loading': '読み込み中...',
    'common.back': '戻る',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.close': '閉じる',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const stored = typeof window !== 'undefined'
      ? (localStorage.getItem('language') as LanguageCode | null)
      : null;
    if (stored && ['en', 'zh', 'ms', 'ja'].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] ?? translations.en[key] ?? key;
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
};
